#!/usr/bin/env python

"""
Usage: test-push <branch-name> <command> <args>...
"""

import subprocess
import sys


def find_commit():
    proc = subprocess.Popen(["git-rev-parse", "HEAD"], stdout=subprocess.PIPE)
    stdout = proc.communicate()[0]
    assert proc.wait() == 0, proc.wait()
    return stdout.rstrip()


def main(args):
    branch = args.pop(0)
    commit = find_commit()
    rc = subprocess.call(args)
    if rc != 0:
        print "command failed; not pushing"
        sys.exit(rc)
    else:
        print "command succeeded; pushing"
        subprocess.check_call(["git-push", ".", "%s:refs/heads/%s" %
                               (commit, branch)])


if __name__ == "__main__":
    main(sys.argv[1:])
