
=head1 NAME

plash-opts, plash-opts-gtk - Set options in the Plash shell

=head1 SYNOPSIS

From the Plash shell:

B<plash-opts> /x=options [I<option-name> I<value>]
B<plash-opts-gtk> /x=options

=head1 DESCRIPTION

The Plash shell has a few options you can set.  There is an object
bound to the variable "options" for setting the options.  These
program will invoke that object.

B<plash-opts-gtk> opens a window using Gtk for setting the options.
B<plash-opts> works just via the command line.

=head1 OPTIONS

=over

=item B<log_summary> I<on>/I<off>
=item B<log_messages> I<on>/I<off>
=item B<log_into_xterm> I<on>/I<off>
=item B<print_fs_tree> I<on>/I<off>
=item B<enable_x11> I<on>/I<off>

=back

=head1 SEE ALSO

plash(1)

/usr/share/doc/plash

=head1 AUTHOR

Mark Seaborn <mseaborn@onetel.com>
