#!/usr/bin/python

"""Run preinst and postinst scripts for Debian packages."""

import os
import sys

import plash.namespace as ns
import plash.mainloop
import plash.process

import plash_pkg.config
import plash_pkg.control
import plash_pkg.launch


unpack_cache = os.path.realpath(plash_pkg.config.get_unpack_cache_dir())

cwd = os.getcwd()
def restore_cwd_hack():
    os.chdir(cwd)


def init_package(app_dir, package, control_script, args):
    my_root = plash_pkg.launch.FileNamespace()
    restore_cwd_hack()
    proc, state = plash_pkg.launch.make_process(app_dir)

    script_path = os.path.join(unpack_cache, package,
                               "control", control_script)

    restore_cwd_hack()
    if os.path.exists(script_path):
        ns.attach_at_path(proc.root_node, "/script",
                          my_root.get_obj(script_path))
        proc.cmd = "/script"
        proc.args = args
        pid = proc.spawn()
        plash.mainloop.run_server()
    else:
        print "  no %s" % control_script

def init_packages(app_dir):
    fh = open(os.path.join(app_dir, "package-list"), "r")
    try:
        for block in plash_pkg.control.file_blocks(fh):
            info = plash_pkg.control.block_fields(block)
            package = "%s_%s" % (info["package"], info["version"])
            print package
            init_package(app_dir, package, "preinst", ["install"])
            init_package(app_dir, package, "postinst", ["configure"])
    finally:
        fh.close()

def main(args):
    if len(args) != 1:
        print "Usage: %s <app-dir>" % sys.argv[0]
    else:
        init_packages(args[0])


if __name__ == "__main__":
    main(sys.argv[1:])
