#!/usr/bin/python

# Copyright (C) 2006, 2007 Mark Seaborn
#
# This file is part of Plash.
#
# Plash is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# Plash is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Plash; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
# USA.

import os
import re
import subprocess

import plash_pkg.config
import plash_pkg.control
import plash_pkg.sources
import plash_pkg.utils


def fetch_packages_file(src, dest_dir, arch):
    url = plash_pkg.utils.join_with_slash(src["S_base"],
                plash_pkg.utils.join_with_slash(src["S_component"],
                                          "binary-%s/Packages.gz" % arch))
    match = re.match("http://(.*)$", url)
    if not match:
        raise Exception("Only HTTP is supported: %s" % url)
    leafname = re.sub("/", "_", match.group(1))
    filename = os.path.join(dest_dir, leafname)
    if not os.path.exists(filename):
        print "Get %s" % url
        subprocess.call(["curl", url, "-o", filename])
    else:
        print "Hit %s" % url
    return filename

def open_gunzip(filename):
    proc = subprocess.Popen(["zcat", filename],
                            stdout=subprocess.PIPE,
                            bufsize=8000)
    return proc.stdout

def combine_package_lists(out, src_list):
    regexp_desc = re.compile(r"^Description:.*\n(\s+.*)*(\n|\Z)", re.M | re.I)
    for src in src_list:
        filename = src["S_file"]
        fh = open_gunzip(filename)
        try:
            for block in plash_pkg.control.file_blocks(fh):
                # Remove the Description field to save space.
                block = "".join(block)
                block = regexp_desc.sub("", block, 1)
                out.write("Base-URL: %s\n" % src["S_base"])
                out.write(block)
                out.write("\n")
        finally:
            fh.close()

def main():
    arch = plash_pkg.config.get_arch()
    output_dir = plash_pkg.config.get_package_list_cache_dir()

    src_list = plash_pkg.sources.read_sources_list("sources.list")
    for src in src_list:
        src["S_file"] = fetch_packages_file(src, output_dir, arch)

    out = open(plash_pkg.config.get_package_list_combined(), "w")
    try:
        combine_package_lists(out, src_list)
    finally:
        out.close()


if __name__ == "__main__":
    main()
