#!/bin/sh

. mrs/config.sh

(
  echo "/* Auto-generated by make-config-h.sh from config.sh */"
  echo "#define JAIL_DIR \"$JAIL_DIR\""
  echo "#define BIN_INSTALL \"$BIN_INSTALL\""
  echo "#define LIB_INSTALL \"$LIB_INSTALL\""
) >mrs/config.h
