/* This file is automatically generated from shell.gram */
#include "region.h"
#include "shell.h"
#include "shell-variants.h"
/* This file is automatically generated */


int f_wschar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ws(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp0(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ampersand(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_plus(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arrow(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_close(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_open(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_number(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_char(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_opt_str(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_option(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_string_literal(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arg(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist4(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist3(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_command(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_fail(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_null(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);

int f_wschar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  if(pos_in1 < end && *pos_in1 == ' ') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label0;
 label0:
  if(pos_in1 < end && *pos_in1 == '\t') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label1;
 label1:
  if(pos_in1 < end && *pos_in1 == '\n') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ws(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  { const char *pos_out; void *ok_val; if(f_tmp0(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp0(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos3;
  void *result5;
  const char *pos10;
  void *result12;
  const char *pos13;
  void *result15;
  const char *pos16;
  void *result18;
  const char *pos6;
  void *result8;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { pos3 = pos_out; result5 = ok_val; goto label4; } else goto label9; }
 label9:
  if(pos_in1 < end && *pos_in1 == '#') { pos10 = pos_in1 + 1; result12 = 0; goto label11; } else goto label2;
 label11:
  { const char *pos_out; void *ok_val; if(f_tmp1(r, pos10, end, &pos_out, &ok_val)) { pos13 = pos_out; result15 = ok_val; goto label14; } else goto label2; }
 label14:
  if(pos13 < end && *pos13 == '\n') { pos16 = pos13 + 1; result18 = 0; goto label17; } else goto label2;
 label17:
  pos3 = pos16;
  { result5 = 0; }
  goto label4;
 label4:
  { const char *pos_out; void *ok_val; if(f_tmp0(r, pos3, end, &pos_out, &ok_val)) { pos6 = pos_out; result8 = ok_val; goto label7; } else goto label2; }
 label7:
  pos_out1 = pos6;
  { void *xs = result8; void *x = result5; ok_val1 = 0; }
  goto ok;
 label2:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos20;
  void *result22;
  const char *pos26;
  void *result28;
  const char *junk_pos32;
  const char *junk_pos33;
  const char *pos29;
  void *result31;
  const char *pos23;
  void *result25;
  if(pos_in1 < end && *pos_in1 == '\n') { junk_pos32 = pos_in1 + 1; junk_pos33 = 0; goto label19; } else goto label34;
 label34:
  pos26 = pos_in1; result28 = 0; goto label27;
 label27:
  if(pos26 < end) { pos29 = pos26 + 1; result31 = (void*) *pos26; goto label30; } else goto label19;
 label30:
  pos20 = pos29;
  { result22 = 0; }
  goto label21;
 label21:
  { const char *pos_out; void *ok_val; if(f_tmp1(r, pos20, end, &pos_out, &ok_val)) { pos23 = pos_out; result25 = ok_val; goto label24; } else goto label19; }
 label24:
  pos_out1 = pos23;
  { void *xs = result25; void *x = result22; ok_val1 = 0; }
  goto ok;
 label19:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ampersand(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos35;
  void *result37;
  const char *pos38;
  void *result40;
  if(pos_in1 + 1 <= end && pos_in1[0] == '&') { pos35 = pos_in1 + 1; result37 = 0; goto label36; } else goto fail;
 label36:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos35, end, &pos_out, &ok_val)) { pos38 = pos_out; result40 = ok_val; goto label39; } else goto fail; }
 label39:
  pos_out1 = pos38;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_plus(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos41;
  void *result43;
  const char *pos44;
  void *result46;
  if(pos_in1 + 1 <= end && pos_in1[0] == '+') { pos41 = pos_in1 + 1; result43 = 0; goto label42; } else goto fail;
 label42:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos41, end, &pos_out, &ok_val)) { pos44 = pos_out; result46 = ok_val; goto label45; } else goto fail; }
 label45:
  pos_out1 = pos44;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arrow(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos47;
  void *result49;
  const char *pos50;
  void *result52;
  if(pos_in1 + 2 <= end && pos_in1[0] == '=' && pos_in1[1] == '>') { pos47 = pos_in1 + 2; result49 = 0; goto label48; } else goto fail;
 label48:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos47, end, &pos_out, &ok_val)) { pos50 = pos_out; result52 = ok_val; goto label51; } else goto fail; }
 label51:
  pos_out1 = pos50;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_close(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos53;
  void *result55;
  const char *pos56;
  void *result58;
  if(pos_in1 < end && *pos_in1 == '}') { pos53 = pos_in1 + 1; result55 = 0; goto label54; } else goto fail;
 label54:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos53, end, &pos_out, &ok_val)) { pos56 = pos_out; result58 = ok_val; goto label57; } else goto fail; }
 label57:
  pos_out1 = pos56;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_open(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos59;
  void *result61;
  const char *pos62;
  void *result64;
  if(pos_in1 < end && *pos_in1 == '{') { pos59 = pos_in1 + 1; result61 = 0; goto label60; } else goto fail;
 label60:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos59, end, &pos_out, &ok_val)) { pos62 = pos_out; result64 = ok_val; goto label63; } else goto fail; }
 label63:
  pos_out1 = pos62;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_number(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos65;
  void *result67;
  const char *pos68;
  void *result70;
  const char *pos72;
  void *result74;
  if(pos_in1 < end && (('0' <= *pos_in1 && *pos_in1 <= '9'))) { pos65 = pos_in1 + 1; result67 = (void*) *pos_in1; goto label66; } else goto fail;
 label66:
  { const char *pos_out; void *ok_val; if(f_number(r, pos65, end, &pos_out, &ok_val)) { pos68 = pos_out; result70 = ok_val; goto label69; } else goto label71; }
 label71:
  { const char *pos_out; void *ok_val; if(f_null(r, pos65, end, &pos_out, &ok_val)) { pos72 = pos_out; result74 = ok_val; goto label73; } else goto fail; }
 label73:
  pos68 = pos72;
  { void *c = result67; result70 = 0; }
  goto label69;
 label69:
  pos_out1 = pos68;
  { void *rest = result70; void *c = result67; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_char(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos126;
  void *result128;
  const char *pos129;
  void *result131;
  const char *pos120;
  void *result122;
  const char *pos123;
  void *result125;
  const char *pos114;
  void *result116;
  const char *pos117;
  void *result119;
  const char *pos108;
  void *result110;
  const char *pos111;
  void *result113;
  const char *pos102;
  void *result104;
  const char *pos105;
  void *result107;
  const char *pos96;
  void *result98;
  const char *pos99;
  void *result101;
  const char *pos81;
  void *result83;
  const char *junk_pos87;
  const char *junk_pos88;
  const char *pos90;
  void *result92;
  const char *pos93;
  void *result95;
  const char *pos84;
  void *result86;
  if(pos_in1 < end && *pos_in1 == '\\') { pos126 = pos_in1 + 1; result128 = 0; goto label127; } else goto label75;
 label127:
  if(pos126 < end && *pos126 == '\\') { pos129 = pos126 + 1; result131 = 0; goto label130; } else goto label75;
 label130:
  pos_out1 = pos129;
  { ok_val1 = (void*) '\\'; }
  goto ok;
 label75:
  if(pos_in1 < end && *pos_in1 == '\\') { pos120 = pos_in1 + 1; result122 = 0; goto label121; } else goto label76;
 label121:
  if(pos120 < end && *pos120 == '\'') { pos123 = pos120 + 1; result125 = 0; goto label124; } else goto label76;
 label124:
  pos_out1 = pos123;
  { ok_val1 = (void*) '\''; }
  goto ok;
 label76:
  if(pos_in1 < end && *pos_in1 == '\\') { pos114 = pos_in1 + 1; result116 = 0; goto label115; } else goto label77;
 label115:
  if(pos114 < end && *pos114 == '"') { pos117 = pos114 + 1; result119 = 0; goto label118; } else goto label77;
 label118:
  pos_out1 = pos117;
  { ok_val1 = (void*) '"'; }
  goto ok;
 label77:
  if(pos_in1 < end && *pos_in1 == '\\') { pos108 = pos_in1 + 1; result110 = 0; goto label109; } else goto label78;
 label109:
  if(pos108 < end && *pos108 == ' ') { pos111 = pos108 + 1; result113 = 0; goto label112; } else goto label78;
 label112:
  pos_out1 = pos111;
  { ok_val1 = (void*) ' '; }
  goto ok;
 label78:
  if(pos_in1 < end && *pos_in1 == '\\') { pos102 = pos_in1 + 1; result104 = 0; goto label103; } else goto label79;
 label103:
  if(pos102 < end && *pos102 == 'n') { pos105 = pos102 + 1; result107 = 0; goto label106; } else goto label79;
 label106:
  pos_out1 = pos105;
  { ok_val1 = (void*) '\n'; }
  goto ok;
 label79:
  if(pos_in1 < end && *pos_in1 == '\\') { pos96 = pos_in1 + 1; result98 = 0; goto label97; } else goto label80;
 label97:
  if(pos96 < end && *pos96 == 't') { pos99 = pos96 + 1; result101 = 0; goto label100; } else goto label80;
 label100:
  pos_out1 = pos99;
  { ok_val1 = (void*) '\t'; }
  goto ok;
 label80:
  if(pos_in1 < end && *pos_in1 == '\\') { pos90 = pos_in1 + 1; result92 = 0; goto label91; } else goto label89;
 label91:
  if(pos90 < end) { pos93 = pos90 + 1; result95 = (void*) *pos90; goto label94; } else goto label89;
 label94:
  junk_pos87 = pos93;
  { junk_pos88 = 0; }
  goto fail;
 label89:
  pos81 = pos_in1; result83 = 0; goto label82;
 label82:
  if(pos81 < end) { pos84 = pos81 + 1; result86 = (void*) *pos81; goto label85; } else goto fail;
 label85:
  pos_out1 = pos84;
  { void *c = result86; ok_val1 = (void*) c; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_opt_str(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos136;
  void *result138;
  const char *junk_pos145;
  const char *junk_pos146;
  const char *pos139;
  void *result141;
  const char *pos142;
  void *result144;
  const char *pos133;
  void *result135;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { junk_pos145 = pos_out; junk_pos146 = ok_val; goto label132; } else goto label147; }
 label147:
  pos136 = pos_in1; result138 = 0; goto label137;
 label137:
  { const char *pos_out; void *ok_val; if(f_char(r, pos136, end, &pos_out, &ok_val)) { pos139 = pos_out; result141 = ok_val; goto label140; } else goto label132; }
 label140:
  { const char *pos_out; void *ok_val; if(f_opt_str(r, pos139, end, &pos_out, &ok_val)) { pos142 = pos_out; result144 = ok_val; goto label143; } else goto label132; }
 label143:
  pos_out1 = pos142;
  { void *rest = result144; void *c = result141; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label132:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos133 = pos_out; result135 = ok_val; goto label134; } else goto fail; }
 label134:
  pos_out1 = pos133;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_option(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos148;
  void *result150;
  const char *pos151;
  void *result153;
  const char *pos154;
  void *result156;
  if(pos_in1 < end && *pos_in1 == '-') { pos148 = pos_in1 + 1; result150 = 0; goto label149; } else goto fail;
 label149:
  { const char *pos_out; void *ok_val; if(f_opt_str(r, pos148, end, &pos_out, &ok_val)) { pos151 = pos_out; result153 = ok_val; goto label152; } else goto fail; }
 label152:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos151, end, &pos_out, &ok_val)) { pos154 = pos_out; result156 = ok_val; goto label155; } else goto fail; }
 label155:
  pos_out1 = pos154;
  { void *s = result153; ok_val1 = char_cons(r, '-', s); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos161;
  void *result163;
  const char *junk_pos170;
  const char *junk_pos171;
  const char *pos164;
  void *result166;
  const char *pos167;
  void *result169;
  const char *pos158;
  void *result160;
  if(pos_in1 < end && *pos_in1 == '\'') { junk_pos170 = pos_in1 + 1; junk_pos171 = 0; goto label157; } else goto label172;
 label172:
  pos161 = pos_in1; result163 = 0; goto label162;
 label162:
  { const char *pos_out; void *ok_val; if(f_char(r, pos161, end, &pos_out, &ok_val)) { pos164 = pos_out; result166 = ok_val; goto label165; } else goto label157; }
 label165:
  { const char *pos_out; void *ok_val; if(f_str_lit2(r, pos164, end, &pos_out, &ok_val)) { pos167 = pos_out; result169 = ok_val; goto label168; } else goto label157; }
 label168:
  pos_out1 = pos167;
  { void *rest = result169; void *c = result166; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label157:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos158 = pos_out; result160 = ok_val; goto label159; } else goto fail; }
 label159:
  pos_out1 = pos158;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos177;
  void *result179;
  const char *junk_pos186;
  const char *junk_pos187;
  const char *pos180;
  void *result182;
  const char *pos183;
  void *result185;
  const char *pos174;
  void *result176;
  if(pos_in1 < end && *pos_in1 == '"') { junk_pos186 = pos_in1 + 1; junk_pos187 = 0; goto label173; } else goto label188;
 label188:
  pos177 = pos_in1; result179 = 0; goto label178;
 label178:
  { const char *pos_out; void *ok_val; if(f_char(r, pos177, end, &pos_out, &ok_val)) { pos180 = pos_out; result182 = ok_val; goto label181; } else goto label173; }
 label181:
  { const char *pos_out; void *ok_val; if(f_str_lit1(r, pos180, end, &pos_out, &ok_val)) { pos183 = pos_out; result185 = ok_val; goto label184; } else goto label173; }
 label184:
  pos_out1 = pos183;
  { void *rest = result185; void *c = result182; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label173:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos174 = pos_out; result176 = ok_val; goto label175; } else goto fail; }
 label175:
  pos_out1 = pos174;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_string_literal(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos202;
  void *result204;
  const char *pos205;
  void *result207;
  const char *pos208;
  void *result210;
  const char *pos211;
  void *result213;
  const char *pos190;
  void *result192;
  const char *pos193;
  void *result195;
  const char *pos196;
  void *result198;
  const char *pos199;
  void *result201;
  if(pos_in1 < end && *pos_in1 == '"') { pos202 = pos_in1 + 1; result204 = 0; goto label203; } else goto label189;
 label203:
  { const char *pos_out; void *ok_val; if(f_str_lit1(r, pos202, end, &pos_out, &ok_val)) { pos205 = pos_out; result207 = ok_val; goto label206; } else goto label189; }
 label206:
  if(pos205 < end && *pos205 == '"') { pos208 = pos205 + 1; result210 = 0; goto label209; } else goto label189;
 label209:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos208, end, &pos_out, &ok_val)) { pos211 = pos_out; result213 = ok_val; goto label212; } else goto label189; }
 label212:
  pos_out1 = pos211;
  { void *s = result207; ok_val1 = s; }
  goto ok;
 label189:
  if(pos_in1 < end && *pos_in1 == '\'') { pos190 = pos_in1 + 1; result192 = 0; goto label191; } else goto fail;
 label191:
  { const char *pos_out; void *ok_val; if(f_str_lit2(r, pos190, end, &pos_out, &ok_val)) { pos193 = pos_out; result195 = ok_val; goto label194; } else goto fail; }
 label194:
  if(pos193 < end && *pos193 == '\'') { pos196 = pos193 + 1; result198 = 0; goto label197; } else goto fail;
 label197:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos196, end, &pos_out, &ok_val)) { pos199 = pos_out; result201 = ok_val; goto label200; } else goto fail; }
 label200:
  pos_out1 = pos199;
  { void *s = result195; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos214;
  void *result216;
  const char *pos224;
  void *result226;
  const char *junk_pos230;
  const char *junk_pos231;
  const char *pos227;
  void *result229;
  const char *pos217;
  void *result219;
  const char *pos221;
  void *result223;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { junk_pos230 = pos_out; junk_pos231 = ok_val; goto fail; } else goto label233; }
 label233:
  if(pos_in1 < end && *pos_in1 == '&') { junk_pos230 = pos_in1 + 1; junk_pos231 = 0; goto fail; } else goto label232;
 label232:
  pos224 = pos_in1; result226 = 0; goto label225;
 label225:
  { const char *pos_out; void *ok_val; if(f_char(r, pos224, end, &pos_out, &ok_val)) { pos227 = pos_out; result229 = ok_val; goto label228; } else goto fail; }
 label228:
  pos214 = pos227;
  { void *c = result229; result216 = (void*) c; }
  goto label215;
 label215:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(r, pos214, end, &pos_out, &ok_val)) { pos217 = pos_out; result219 = ok_val; goto label218; } else goto label220; }
 label220:
  { const char *pos_out; void *ok_val; if(f_null(r, pos214, end, &pos_out, &ok_val)) { pos221 = pos_out; result223 = ok_val; goto label222; } else goto fail; }
 label222:
  pos217 = pos221;
  { void *c = result216; result219 = 0; }
  goto label218;
 label218:
  pos_out1 = pos217;
  { void *rest = result219; void *c = result216; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos234;
  void *result236;
  const char *junk_pos243;
  const char *junk_pos244;
  const char *junk_pos246;
  const char *junk_pos247;
  const char *pos237;
  void *result239;
  const char *pos240;
  void *result242;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_' || *pos_in1 == '/' || *pos_in1 == '.' || *pos_in1 == '~')) { junk_pos246 = pos_in1 + 1; junk_pos247 = (void*) *pos_in1; goto label245; } else goto label248;
 label248:
  junk_pos243 = pos_in1; junk_pos244 = 0; goto fail;
 label245:
  pos234 = pos_in1; result236 = 0; goto label235;
 label235:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(r, pos234, end, &pos_out, &ok_val)) { pos237 = pos_out; result239 = ok_val; goto label238; } else goto fail; }
 label238:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos237, end, &pos_out, &ok_val)) { pos240 = pos_out; result242 = ok_val; goto label241; } else goto fail; }
 label241:
  pos_out1 = pos240;
  { void *s = result239; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arg(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos257;
  void *result259;
  const char *pos254;
  void *result256;
  const char *pos251;
  void *result253;
  { const char *pos_out; void *ok_val; if(f_option(r, pos_in1, end, &pos_out, &ok_val)) { pos257 = pos_out; result259 = ok_val; goto label258; } else goto label249; }
 label258:
  pos_out1 = pos257;
  { void *s = result259; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label249:
  { const char *pos_out; void *ok_val; if(f_string_literal(r, pos_in1, end, &pos_out, &ok_val)) { pos254 = pos_out; result256 = ok_val; goto label255; } else goto label250; }
 label255:
  pos_out1 = pos254;
  { void *s = result256; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label250:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos_in1, end, &pos_out, &ok_val)) { pos251 = pos_out; result253 = ok_val; goto label252; } else goto fail; }
 label252:
  pos_out1 = pos251;
  { void *f = result253; ok_val1 = mk_arg_filename(r, f); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist4(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos261;
  void *result263;
  const char *pos264;
  void *result266;
  const char *pos267;
  void *result269;
  { const char *pos_out; void *ok_val; if(f_c_open(r, pos_in1, end, &pos_out, &ok_val)) { pos261 = pos_out; result263 = ok_val; goto label262; } else goto label260; }
 label262:
  { const char *pos_out; void *ok_val; if(f_arglist1(r, pos261, end, &pos_out, &ok_val)) { pos264 = pos_out; result266 = ok_val; goto label265; } else goto label260; }
 label265:
  { const char *pos_out; void *ok_val; if(f_c_close(r, pos264, end, &pos_out, &ok_val)) { pos267 = pos_out; result269 = ok_val; goto label268; } else goto label260; }
 label268:
  pos_out1 = pos267;
  { void *l = result266; ok_val1 = l; }
  goto ok;
 label260:
  { const char *pos_out; void *ok_val; if(f_arg(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist3(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos274;
  void *result276;
  const char *pos277;
  void *result279;
  const char *pos271;
  void *result273;
  { const char *pos_out; void *ok_val; if(f_arglist4(r, pos_in1, end, &pos_out, &ok_val)) { pos274 = pos_out; result276 = ok_val; goto label275; } else goto label270; }
 label275:
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos274, end, &pos_out, &ok_val)) { pos277 = pos_out; result279 = ok_val; goto label278; } else goto label270; }
 label278:
  pos_out1 = pos277;
  { void *a2 = result279; void *a1 = result276; ok_val1 = mk_arg_cat(r, a1, a2); }
  goto ok;
 label270:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos271 = pos_out; result273 = ok_val; goto label272; } else goto fail; }
 label272:
  pos_out1 = pos271;
  { ok_val1 = mk_arg_empty(r); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos281;
  void *result283;
  const char *pos284;
  void *result286;
  const char *pos287;
  void *result289;
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos_in1, end, &pos_out, &ok_val)) { pos281 = pos_out; result283 = ok_val; goto label282; } else goto label280; }
 label282:
  { const char *pos_out; void *ok_val; if(f_plus(r, pos281, end, &pos_out, &ok_val)) { pos284 = pos_out; result286 = ok_val; goto label285; } else goto label280; }
 label285:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos284, end, &pos_out, &ok_val)) { pos287 = pos_out; result289 = ok_val; goto label288; } else goto label280; }
 label288:
  pos_out1 = pos287;
  { void *fs = result289; void *a = result283; ok_val1 = mk_arg_cat(r, a, mk_arg_ambient(r, fs)); }
  goto ok;
 label280:
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos291;
  void *result293;
  const char *pos294;
  void *result296;
  const char *pos297;
  void *result299;
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos_in1, end, &pos_out, &ok_val)) { pos291 = pos_out; result293 = ok_val; goto label292; } else goto label290; }
 label292:
  { const char *pos_out; void *ok_val; if(f_arrow(r, pos291, end, &pos_out, &ok_val)) { pos294 = pos_out; result296 = ok_val; goto label295; } else goto label290; }
 label295:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos294, end, &pos_out, &ok_val)) { pos297 = pos_out; result299 = ok_val; goto label298; } else goto label290; }
 label298:
  pos_out1 = pos297;
  { void *a2 = result299; void *a1 = result293; ok_val1 = mk_arg_cat(r, mk_arg_read(r, a1), mk_arg_write(r, a2)); }
  goto ok;
 label290:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_command(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos350;
  void *result352;
  const char *pos353;
  void *result355;
  const char *pos356;
  void *result358;
  const char *pos344;
  void *result346;
  const char *pos347;
  void *result349;
  const char *pos332;
  void *result334;
  const char *pos335;
  void *result337;
  const char *pos338;
  void *result340;
  const char *pos341;
  void *result343;
  const char *pos320;
  void *result322;
  const char *pos323;
  void *result325;
  const char *pos326;
  void *result328;
  const char *pos329;
  void *result331;
  const char *pos304;
  void *result306;
  const char *pos307;
  void *result309;
  const char *pos310;
  void *result312;
  const char *pos317;
  void *result319;
  const char *pos314;
  void *result316;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos350 = pos_in1 + 2; result352 = 0; goto label351; } else goto label300;
 label351:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos350, end, &pos_out, &ok_val)) { pos353 = pos_out; result355 = ok_val; goto label354; } else goto label300; }
 label354:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos353, end, &pos_out, &ok_val)) { pos356 = pos_out; result358 = ok_val; goto label357; } else goto label300; }
 label357:
  pos_out1 = pos356;
  { void *dir = result358; ok_val1 = mk_chdir(r, dir); }
  goto ok;
 label300:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos344 = pos_in1 + 2; result346 = 0; goto label345; } else goto label301;
 label345:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos344, end, &pos_out, &ok_val)) { pos347 = pos_out; result349 = ok_val; goto label348; } else goto label301; }
 label348:
  pos_out1 = pos347;
  { ok_val1 = mk_chdir(r, char_cons(r, '~', 0)); }
  goto ok;
 label301:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'f' && pos_in1[1] == 'g') { pos332 = pos_in1 + 2; result334 = 0; goto label333; } else goto label302;
 label333:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos332, end, &pos_out, &ok_val)) { pos335 = pos_out; result337 = ok_val; goto label336; } else goto label302; }
 label336:
  { const char *pos_out; void *ok_val; if(f_number(r, pos335, end, &pos_out, &ok_val)) { pos338 = pos_out; result340 = ok_val; goto label339; } else goto label302; }
 label339:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos338, end, &pos_out, &ok_val)) { pos341 = pos_out; result343 = ok_val; goto label342; } else goto label302; }
 label342:
  pos_out1 = pos341;
  { void *n = result340; ok_val1 = mk_command_fg(r, n); }
  goto ok;
 label302:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'b' && pos_in1[1] == 'g') { pos320 = pos_in1 + 2; result322 = 0; goto label321; } else goto label303;
 label321:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos320, end, &pos_out, &ok_val)) { pos323 = pos_out; result325 = ok_val; goto label324; } else goto label303; }
 label324:
  { const char *pos_out; void *ok_val; if(f_number(r, pos323, end, &pos_out, &ok_val)) { pos326 = pos_out; result328 = ok_val; goto label327; } else goto label303; }
 label327:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos326, end, &pos_out, &ok_val)) { pos329 = pos_out; result331 = ok_val; goto label330; } else goto label303; }
 label330:
  pos_out1 = pos329;
  { void *n = result328; ok_val1 = mk_command_bg(r, n); }
  goto ok;
 label303:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos_in1, end, &pos_out, &ok_val)) { pos304 = pos_out; result306 = ok_val; goto label305; } else goto fail; }
 label305:
  { const char *pos_out; void *ok_val; if(f_arglist1(r, pos304, end, &pos_out, &ok_val)) { pos307 = pos_out; result309 = ok_val; goto label308; } else goto fail; }
 label308:
  { const char *pos_out; void *ok_val; if(f_ampersand(r, pos307, end, &pos_out, &ok_val)) { pos317 = pos_out; result319 = ok_val; goto label318; } else goto label313; }
 label318:
  pos310 = pos317;
  { void *a = result309; void *c = result306; result312 = 1; }
  goto label311;
 label313:
  { const char *pos_out; void *ok_val; if(f_null(r, pos307, end, &pos_out, &ok_val)) { pos314 = pos_out; result316 = ok_val; goto label315; } else goto fail; }
 label315:
  pos310 = pos314;
  { void *a = result309; void *c = result306; result312 = 0; }
  goto label311;
 label311:
  pos_out1 = pos310;
  { void *bg_flag = result312; void *a = result309; void *c = result306; ok_val1 = mk_command(r, c, a, bg_flag); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_fail(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_null(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  pos_out1 = pos_in1;
  ok_val1 = 0;
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}
