/* This file is automatically generated from shell.gram */
#include "region.h"
#include "shell.h"
#include "shell-variants.h"
/* This file is automatically generated */


int f_wschar(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ws(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_equals(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_bang_bang(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pipe_bar(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ampersand(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_plus(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arrow(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_b_close(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_b_open(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_close(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_open(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_expr2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_expr1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_var_name_aux(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_var_name(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_number(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_char(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_opt_str(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_option(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_string_literal(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_user_name(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_leafname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname_aux3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname_aux2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname_aux1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp0(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname_aux(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_redirection(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arg(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist4(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_invocation(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pipeline(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_command(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_fail(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_null(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);

int f_wschar(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == ' ') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label0;
 label0:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\t') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label1;
 label1:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\n') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ws(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  { const char *pos_out; void *ok_val; if(f_tmp2(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos3;
  void *result5;
  const char *pos10;
  void *result12;
  const char *pos13;
  void *result15;
  const char *pos16;
  void *result18;
  const char *pos6;
  void *result8;
  { const char *pos_out; void *ok_val; if(f_wschar(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos3 = pos_out; result5 = ok_val; goto label4; } else goto label9; }
 label9:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '#') { pos10 = pos_in1 + 1; result12 = 0; goto label11; } else goto label2;
 label11:
  { const char *pos_out; void *ok_val; if(f_tmp3(err_pos, r, pos10, end, &pos_out, &ok_val)) { pos13 = pos_out; result15 = ok_val; goto label14; } else goto label2; }
 label14:
  if(*err_pos < pos13) *err_pos = pos13;
  if(pos13 < end && *pos13 == '\n') { pos16 = pos13 + 1; result18 = 0; goto label17; } else goto label2;
 label17:
  pos3 = pos16;
  { result5 = 0; }
  goto label4;
 label4:
  { const char *pos_out; void *ok_val; if(f_tmp2(err_pos, r, pos3, end, &pos_out, &ok_val)) { pos6 = pos_out; result8 = ok_val; goto label7; } else goto label2; }
 label7:
  pos_out1 = pos6;
  { void *xs = result8; void *x = result5; ok_val1 = 0; }
  goto ok;
 label2:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos20;
  void *result22;
  const char *pos26;
  void *result28;
  const char *junk_pos32;
  const char *junk_pos33;
  const char *pos29;
  void *result31;
  const char *pos23;
  void *result25;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\n') { junk_pos32 = pos_in1 + 1; junk_pos33 = 0; goto label19; } else goto label34;
 label34:
  pos26 = pos_in1; result28 = 0; goto label27;
 label27:
  if(*err_pos < pos26) *err_pos = pos26;
  if(pos26 < end) { pos29 = pos26 + 1; result31 = (void*) (int) *pos26; goto label30; } else goto label19;
 label30:
  pos20 = pos29;
  { result22 = 0; }
  goto label21;
 label21:
  { const char *pos_out; void *ok_val; if(f_tmp3(err_pos, r, pos20, end, &pos_out, &ok_val)) { pos23 = pos_out; result25 = ok_val; goto label24; } else goto label19; }
 label24:
  pos_out1 = pos23;
  { void *xs = result25; void *x = result22; ok_val1 = 0; }
  goto ok;
 label19:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_equals(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos35;
  void *result37;
  const char *pos38;
  void *result40;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '=') { pos35 = pos_in1 + 1; result37 = 0; goto label36; } else goto fail;
 label36:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos35, end, &pos_out, &ok_val)) { pos38 = pos_out; result40 = ok_val; goto label39; } else goto fail; }
 label39:
  pos_out1 = pos38;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_bang_bang(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos41;
  void *result43;
  const char *pos44;
  void *result46;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == '!' && pos_in1[1] == '!') { pos41 = pos_in1 + 2; result43 = 0; goto label42; } else goto fail;
 label42:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos41, end, &pos_out, &ok_val)) { pos44 = pos_out; result46 = ok_val; goto label45; } else goto fail; }
 label45:
  pos_out1 = pos44;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pipe_bar(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos47;
  void *result49;
  const char *pos50;
  void *result52;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '|') { pos47 = pos_in1 + 1; result49 = 0; goto label48; } else goto fail;
 label48:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos47, end, &pos_out, &ok_val)) { pos50 = pos_out; result52 = ok_val; goto label51; } else goto fail; }
 label51:
  pos_out1 = pos50;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ampersand(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos53;
  void *result55;
  const char *pos56;
  void *result58;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '&') { pos53 = pos_in1 + 1; result55 = 0; goto label54; } else goto fail;
 label54:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos53, end, &pos_out, &ok_val)) { pos56 = pos_out; result58 = ok_val; goto label57; } else goto fail; }
 label57:
  pos_out1 = pos56;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_plus(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos59;
  void *result61;
  const char *pos62;
  void *result64;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '+') { pos59 = pos_in1 + 1; result61 = 0; goto label60; } else goto fail;
 label60:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos59, end, &pos_out, &ok_val)) { pos62 = pos_out; result64 = ok_val; goto label63; } else goto fail; }
 label63:
  pos_out1 = pos62;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arrow(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos65;
  void *result67;
  const char *pos68;
  void *result70;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == '=' && pos_in1[1] == '>') { pos65 = pos_in1 + 2; result67 = 0; goto label66; } else goto fail;
 label66:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos65, end, &pos_out, &ok_val)) { pos68 = pos_out; result70 = ok_val; goto label69; } else goto fail; }
 label69:
  pos_out1 = pos68;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_b_close(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos71;
  void *result73;
  const char *pos74;
  void *result76;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == ')') { pos71 = pos_in1 + 1; result73 = 0; goto label72; } else goto fail;
 label72:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos71, end, &pos_out, &ok_val)) { pos74 = pos_out; result76 = ok_val; goto label75; } else goto fail; }
 label75:
  pos_out1 = pos74;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_b_open(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos77;
  void *result79;
  const char *pos80;
  void *result82;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '(') { pos77 = pos_in1 + 1; result79 = 0; goto label78; } else goto fail;
 label78:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos77, end, &pos_out, &ok_val)) { pos80 = pos_out; result82 = ok_val; goto label81; } else goto fail; }
 label81:
  pos_out1 = pos80;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_close(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos83;
  void *result85;
  const char *pos86;
  void *result88;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '}') { pos83 = pos_in1 + 1; result85 = 0; goto label84; } else goto fail;
 label84:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos83, end, &pos_out, &ok_val)) { pos86 = pos_out; result88 = ok_val; goto label87; } else goto fail; }
 label87:
  pos_out1 = pos86;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_open(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos89;
  void *result91;
  const char *pos92;
  void *result94;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '{') { pos89 = pos_in1 + 1; result91 = 0; goto label90; } else goto fail;
 label90:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos89, end, &pos_out, &ok_val)) { pos92 = pos_out; result94 = ok_val; goto label93; } else goto fail; }
 label93:
  pos_out1 = pos92;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_expr2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos105;
  void *result107;
  const char *pos96;
  void *result98;
  const char *pos99;
  void *result101;
  const char *pos102;
  void *result104;
  { const char *pos_out; void *ok_val; if(f_var_name(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos105 = pos_out; result107 = ok_val; goto label106; } else goto label95; }
 label106:
  pos_out1 = pos105;
  { void *v = result107; ok_val1 = mk_expr_var(r, v); }
  goto ok;
 label95:
  { const char *pos_out; void *ok_val; if(f_b_open(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos96 = pos_out; result98 = ok_val; goto label97; } else goto fail; }
 label97:
  { const char *pos_out; void *ok_val; if(f_expr1(err_pos, r, pos96, end, &pos_out, &ok_val)) { pos99 = pos_out; result101 = ok_val; goto label100; } else goto fail; }
 label100:
  { const char *pos_out; void *ok_val; if(f_b_close(err_pos, r, pos99, end, &pos_out, &ok_val)) { pos102 = pos_out; result104 = ok_val; goto label103; } else goto fail; }
 label103:
  pos_out1 = pos102;
  { void *e = result101; ok_val1 = e; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_expr1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos125;
  void *result127;
  const char *pos128;
  void *result130;
  const char *junk_pos140;
  const char *junk_pos141;
  const char *pos131;
  void *result133;
  const char *pos134;
  void *result136;
  const char *pos137;
  void *result139;
  const char *pos110;
  void *result112;
  const char *pos113;
  void *result115;
  const char *junk_pos122;
  const char *junk_pos123;
  const char *pos116;
  void *result118;
  const char *pos119;
  void *result121;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 6 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'a' && pos_in1[2] == 'p' && pos_in1[3] == 'c' && pos_in1[4] == 'm' && pos_in1[5] == 'd') { pos125 = pos_in1 + 6; result127 = 0; goto label126; } else goto label108;
 label126:
  if(*err_pos < pos125) *err_pos = pos125;
  if(pos125 < end && (('a' <= *pos125 && *pos125 <= 'z') || ('A' <= *pos125 && *pos125 <= 'Z') || ('0' <= *pos125 && *pos125 <= '9') || *pos125 == '_')) { junk_pos140 = pos125 + 1; junk_pos141 = (void*) (int) *pos125; goto label108; } else goto label142;
 label142:
  pos128 = pos125; result130 = 0; goto label129;
 label129:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos128, end, &pos_out, &ok_val)) { pos131 = pos_out; result133 = ok_val; goto label132; } else goto label108; }
 label132:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos131, end, &pos_out, &ok_val)) { pos134 = pos_out; result136 = ok_val; goto label135; } else goto label108; }
 label135:
  { const char *pos_out; void *ok_val; if(f_arglist1(err_pos, r, pos134, end, &pos_out, &ok_val)) { pos137 = pos_out; result139 = ok_val; goto label138; } else goto label108; }
 label138:
  pos_out1 = pos137;
  { void *args = result139; void *cmd = result136; ok_val1 = mk_cap_cmd(r, cmd, args); }
  goto ok;
 label108:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 1 <= end && pos_in1[0] == 'F') { pos110 = pos_in1 + 1; result112 = 0; goto label111; } else goto label109;
 label111:
  if(*err_pos < pos110) *err_pos = pos110;
  if(pos110 < end && (('a' <= *pos110 && *pos110 <= 'z') || ('A' <= *pos110 && *pos110 <= 'Z') || ('0' <= *pos110 && *pos110 <= '9') || *pos110 == '_')) { junk_pos122 = pos110 + 1; junk_pos123 = (void*) (int) *pos110; goto label109; } else goto label124;
 label124:
  pos113 = pos110; result115 = 0; goto label114;
 label114:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos113, end, &pos_out, &ok_val)) { pos116 = pos_out; result118 = ok_val; goto label117; } else goto label109; }
 label117:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos116, end, &pos_out, &ok_val)) { pos119 = pos_out; result121 = ok_val; goto label120; } else goto label109; }
 label120:
  pos_out1 = pos119;
  { void *f = result121; ok_val1 = mk_expr_filename(r, f); }
  goto ok;
 label109:
  { const char *pos_out; void *ok_val; if(f_expr2(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_var_name_aux(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos150;
  void *result152;
  const char *pos144;
  void *result146;
  const char *pos147;
  void *result149;
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos150 = pos_out; result152 = ok_val; goto label151; } else goto label143; }
 label151:
  pos_out1 = pos150;
  { ok_val1 = 0; }
  goto ok;
 label143:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_')) { pos144 = pos_in1 + 1; result146 = (void*) (int) *pos_in1; goto label145; } else goto fail;
 label145:
  { const char *pos_out; void *ok_val; if(f_var_name_aux(err_pos, r, pos144, end, &pos_out, &ok_val)) { pos147 = pos_out; result149 = ok_val; goto label148; } else goto fail; }
 label148:
  pos_out1 = pos147;
  { void *rest = result149; void *c = result146; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_var_name(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos153;
  void *result155;
  const char *pos156;
  void *result158;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || *pos_in1 == '_')) { pos153 = pos_in1 + 1; result155 = (void*) (int) *pos_in1; goto label154; } else goto fail;
 label154:
  { const char *pos_out; void *ok_val; if(f_var_name_aux(err_pos, r, pos153, end, &pos_out, &ok_val)) { pos156 = pos_out; result158 = ok_val; goto label157; } else goto fail; }
 label157:
  pos_out1 = pos156;
  { void *rest = result158; void *c = result155; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_number(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos159;
  void *result161;
  const char *pos162;
  void *result164;
  const char *pos166;
  void *result168;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (('0' <= *pos_in1 && *pos_in1 <= '9'))) { pos159 = pos_in1 + 1; result161 = (void*) (int) *pos_in1; goto label160; } else goto fail;
 label160:
  { const char *pos_out; void *ok_val; if(f_number(err_pos, r, pos159, end, &pos_out, &ok_val)) { pos162 = pos_out; result164 = ok_val; goto label163; } else goto label165; }
 label165:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos159, end, &pos_out, &ok_val)) { pos166 = pos_out; result168 = ok_val; goto label167; } else goto fail; }
 label167:
  pos162 = pos166;
  { void *c = result161; result164 = 0; }
  goto label163;
 label163:
  pos_out1 = pos162;
  { void *rest = result164; void *c = result161; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_char(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos227;
  void *result229;
  const char *pos230;
  void *result232;
  const char *pos221;
  void *result223;
  const char *pos224;
  void *result226;
  const char *pos215;
  void *result217;
  const char *pos218;
  void *result220;
  const char *pos209;
  void *result211;
  const char *pos212;
  void *result214;
  const char *pos203;
  void *result205;
  const char *pos206;
  void *result208;
  const char *pos197;
  void *result199;
  const char *pos200;
  void *result202;
  const char *pos191;
  void *result193;
  const char *pos194;
  void *result196;
  const char *pos176;
  void *result178;
  const char *junk_pos182;
  const char *junk_pos183;
  const char *pos185;
  void *result187;
  const char *pos188;
  void *result190;
  const char *pos179;
  void *result181;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos227 = pos_in1 + 1; result229 = 0; goto label228; } else goto label169;
 label228:
  if(*err_pos < pos227) *err_pos = pos227;
  if(pos227 < end && *pos227 == '\\') { pos230 = pos227 + 1; result232 = 0; goto label231; } else goto label169;
 label231:
  pos_out1 = pos230;
  { ok_val1 = (void*) '\\'; }
  goto ok;
 label169:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos221 = pos_in1 + 1; result223 = 0; goto label222; } else goto label170;
 label222:
  if(*err_pos < pos221) *err_pos = pos221;
  if(pos221 < end && *pos221 == '\'') { pos224 = pos221 + 1; result226 = 0; goto label225; } else goto label170;
 label225:
  pos_out1 = pos224;
  { ok_val1 = (void*) '\''; }
  goto ok;
 label170:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos215 = pos_in1 + 1; result217 = 0; goto label216; } else goto label171;
 label216:
  if(*err_pos < pos215) *err_pos = pos215;
  if(pos215 < end && *pos215 == '"') { pos218 = pos215 + 1; result220 = 0; goto label219; } else goto label171;
 label219:
  pos_out1 = pos218;
  { ok_val1 = (void*) '"'; }
  goto ok;
 label171:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos209 = pos_in1 + 1; result211 = 0; goto label210; } else goto label172;
 label210:
  if(*err_pos < pos209) *err_pos = pos209;
  if(pos209 < end && *pos209 == ' ') { pos212 = pos209 + 1; result214 = 0; goto label213; } else goto label172;
 label213:
  pos_out1 = pos212;
  { ok_val1 = (void*) ' '; }
  goto ok;
 label172:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos203 = pos_in1 + 1; result205 = 0; goto label204; } else goto label173;
 label204:
  if(*err_pos < pos203) *err_pos = pos203;
  if(pos203 < end && *pos203 == 'n') { pos206 = pos203 + 1; result208 = 0; goto label207; } else goto label173;
 label207:
  pos_out1 = pos206;
  { ok_val1 = (void*) '\n'; }
  goto ok;
 label173:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos197 = pos_in1 + 1; result199 = 0; goto label198; } else goto label174;
 label198:
  if(*err_pos < pos197) *err_pos = pos197;
  if(pos197 < end && *pos197 == 't') { pos200 = pos197 + 1; result202 = 0; goto label201; } else goto label174;
 label201:
  pos_out1 = pos200;
  { ok_val1 = (void*) '\t'; }
  goto ok;
 label174:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos191 = pos_in1 + 1; result193 = 0; goto label192; } else goto label175;
 label192:
  if(*err_pos < pos191) *err_pos = pos191;
  if(pos191 < end && (*pos191 == '&' || *pos191 == '|' || *pos191 == '*' || *pos191 == '+' || *pos191 == '=' || *pos191 == '{' || *pos191 == '}' || *pos191 == '(' || *pos191 == ')')) { pos194 = pos191 + 1; result196 = (void*) (int) *pos191; goto label195; } else goto label175;
 label195:
  pos_out1 = pos194;
  { void *c = result196; ok_val1 = (void*) c; }
  goto ok;
 label175:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\\') { pos185 = pos_in1 + 1; result187 = 0; goto label186; } else goto label184;
 label186:
  if(*err_pos < pos185) *err_pos = pos185;
  if(pos185 < end) { pos188 = pos185 + 1; result190 = (void*) (int) *pos185; goto label189; } else goto label184;
 label189:
  junk_pos182 = pos188;
  { junk_pos183 = 0; }
  goto fail;
 label184:
  pos176 = pos_in1; result178 = 0; goto label177;
 label177:
  if(*err_pos < pos176) *err_pos = pos176;
  if(pos176 < end) { pos179 = pos176 + 1; result181 = (void*) (int) *pos176; goto label180; } else goto fail;
 label180:
  pos_out1 = pos179;
  { void *c = result181; ok_val1 = (void*) c; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_opt_str(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos237;
  void *result239;
  const char *junk_pos246;
  const char *junk_pos247;
  const char *pos240;
  void *result242;
  const char *pos243;
  void *result245;
  const char *pos234;
  void *result236;
  { const char *pos_out; void *ok_val; if(f_wschar(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { junk_pos246 = pos_out; junk_pos247 = ok_val; goto label233; } else goto label248; }
 label248:
  pos237 = pos_in1; result239 = 0; goto label238;
 label238:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos237, end, &pos_out, &ok_val)) { pos240 = pos_out; result242 = ok_val; goto label241; } else goto label233; }
 label241:
  { const char *pos_out; void *ok_val; if(f_opt_str(err_pos, r, pos240, end, &pos_out, &ok_val)) { pos243 = pos_out; result245 = ok_val; goto label244; } else goto label233; }
 label244:
  pos_out1 = pos243;
  { void *rest = result245; void *c = result242; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label233:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos234 = pos_out; result236 = ok_val; goto label235; } else goto fail; }
 label235:
  pos_out1 = pos234;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_option(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos249;
  void *result251;
  const char *pos252;
  void *result254;
  const char *pos255;
  void *result257;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '-') { pos249 = pos_in1 + 1; result251 = 0; goto label250; } else goto fail;
 label250:
  { const char *pos_out; void *ok_val; if(f_opt_str(err_pos, r, pos249, end, &pos_out, &ok_val)) { pos252 = pos_out; result254 = ok_val; goto label253; } else goto fail; }
 label253:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos252, end, &pos_out, &ok_val)) { pos255 = pos_out; result257 = ok_val; goto label256; } else goto fail; }
 label256:
  pos_out1 = pos255;
  { void *s = result254; ok_val1 = char_cons(r, '-', s); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos262;
  void *result264;
  const char *junk_pos271;
  const char *junk_pos272;
  const char *pos265;
  void *result267;
  const char *pos268;
  void *result270;
  const char *pos259;
  void *result261;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\'') { junk_pos271 = pos_in1 + 1; junk_pos272 = 0; goto label258; } else goto label273;
 label273:
  pos262 = pos_in1; result264 = 0; goto label263;
 label263:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos262, end, &pos_out, &ok_val)) { pos265 = pos_out; result267 = ok_val; goto label266; } else goto label258; }
 label266:
  { const char *pos_out; void *ok_val; if(f_str_lit2(err_pos, r, pos265, end, &pos_out, &ok_val)) { pos268 = pos_out; result270 = ok_val; goto label269; } else goto label258; }
 label269:
  pos_out1 = pos268;
  { void *rest = result270; void *c = result267; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label258:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos259 = pos_out; result261 = ok_val; goto label260; } else goto fail; }
 label260:
  pos_out1 = pos259;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos278;
  void *result280;
  const char *junk_pos287;
  const char *junk_pos288;
  const char *pos281;
  void *result283;
  const char *pos284;
  void *result286;
  const char *pos275;
  void *result277;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '"') { junk_pos287 = pos_in1 + 1; junk_pos288 = 0; goto label274; } else goto label289;
 label289:
  pos278 = pos_in1; result280 = 0; goto label279;
 label279:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos278, end, &pos_out, &ok_val)) { pos281 = pos_out; result283 = ok_val; goto label282; } else goto label274; }
 label282:
  { const char *pos_out; void *ok_val; if(f_str_lit1(err_pos, r, pos281, end, &pos_out, &ok_val)) { pos284 = pos_out; result286 = ok_val; goto label285; } else goto label274; }
 label285:
  pos_out1 = pos284;
  { void *rest = result286; void *c = result283; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label274:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos275 = pos_out; result277 = ok_val; goto label276; } else goto fail; }
 label276:
  pos_out1 = pos275;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_string_literal(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos303;
  void *result305;
  const char *pos306;
  void *result308;
  const char *pos309;
  void *result311;
  const char *pos312;
  void *result314;
  const char *pos291;
  void *result293;
  const char *pos294;
  void *result296;
  const char *pos297;
  void *result299;
  const char *pos300;
  void *result302;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '"') { pos303 = pos_in1 + 1; result305 = 0; goto label304; } else goto label290;
 label304:
  { const char *pos_out; void *ok_val; if(f_str_lit1(err_pos, r, pos303, end, &pos_out, &ok_val)) { pos306 = pos_out; result308 = ok_val; goto label307; } else goto label290; }
 label307:
  if(*err_pos < pos306) *err_pos = pos306;
  if(pos306 < end && *pos306 == '"') { pos309 = pos306 + 1; result311 = 0; goto label310; } else goto label290;
 label310:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos309, end, &pos_out, &ok_val)) { pos312 = pos_out; result314 = ok_val; goto label313; } else goto label290; }
 label313:
  pos_out1 = pos312;
  { void *s = result308; ok_val1 = s; }
  goto ok;
 label290:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '\'') { pos291 = pos_in1 + 1; result293 = 0; goto label292; } else goto fail;
 label292:
  { const char *pos_out; void *ok_val; if(f_str_lit2(err_pos, r, pos291, end, &pos_out, &ok_val)) { pos294 = pos_out; result296 = ok_val; goto label295; } else goto fail; }
 label295:
  if(*err_pos < pos294) *err_pos = pos294;
  if(pos294 < end && *pos294 == '\'') { pos297 = pos294 + 1; result299 = 0; goto label298; } else goto fail;
 label298:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos297, end, &pos_out, &ok_val)) { pos300 = pos_out; result302 = ok_val; goto label301; } else goto fail; }
 label301:
  pos_out1 = pos300;
  { void *s = result296; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_user_name(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos315;
  void *result317;
  const char *junk_pos328;
  const char *junk_pos329;
  const char *pos318;
  void *result320;
  const char *pos321;
  void *result323;
  const char *pos325;
  void *result327;
  { const char *pos_out; void *ok_val; if(f_wschar(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { junk_pos328 = pos_out; junk_pos329 = ok_val; goto fail; } else goto label331; }
 label331:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (*pos_in1 == '&' || *pos_in1 == '|' || *pos_in1 == '*' || *pos_in1 == '/' || *pos_in1 == '=' || *pos_in1 == '{' || *pos_in1 == '}' || *pos_in1 == '(' || *pos_in1 == ')')) { junk_pos328 = pos_in1 + 1; junk_pos329 = (void*) (int) *pos_in1; goto fail; } else goto label330;
 label330:
  pos315 = pos_in1; result317 = 0; goto label316;
 label316:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos315, end, &pos_out, &ok_val)) { pos318 = pos_out; result320 = ok_val; goto label319; } else goto fail; }
 label319:
  { const char *pos_out; void *ok_val; if(f_user_name(err_pos, r, pos318, end, &pos_out, &ok_val)) { pos321 = pos_out; result323 = ok_val; goto label322; } else goto label324; }
 label324:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos318, end, &pos_out, &ok_val)) { pos325 = pos_out; result327 = ok_val; goto label326; } else goto fail; }
 label326:
  pos321 = pos325;
  { void *c = result320; result323 = 0; }
  goto label322;
 label322:
  pos_out1 = pos321;
  { void *rest = result323; void *c = result320; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_leafname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos332;
  void *result334;
  const char *pos346;
  void *result348;
  const char *junk_pos352;
  const char *junk_pos353;
  const char *pos349;
  void *result351;
  const char *pos343;
  void *result345;
  const char *pos335;
  void *result337;
  const char *pos339;
  void *result341;
  { const char *pos_out; void *ok_val; if(f_wschar(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { junk_pos352 = pos_out; junk_pos353 = ok_val; goto label342; } else goto label355; }
 label355:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (*pos_in1 == '&' || *pos_in1 == '|' || *pos_in1 == '/' || *pos_in1 == '*' || *pos_in1 == '=' || *pos_in1 == '{' || *pos_in1 == '}' || *pos_in1 == '(' || *pos_in1 == ')')) { junk_pos352 = pos_in1 + 1; junk_pos353 = (void*) (int) *pos_in1; goto label342; } else goto label354;
 label354:
  pos346 = pos_in1; result348 = 0; goto label347;
 label347:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos346, end, &pos_out, &ok_val)) { pos349 = pos_out; result351 = ok_val; goto label350; } else goto label342; }
 label350:
  pos332 = pos349;
  { void *c = result351; result334 = (void*) c; }
  goto label333;
 label342:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '*') { pos343 = pos_in1 + 1; result345 = 0; goto label344; } else goto fail;
 label344:
  pos332 = pos343;
  { result334 = (void*) GLOB_STAR; }
  goto label333;
 label333:
  { const char *pos_out; void *ok_val; if(f_glob_leafname(err_pos, r, pos332, end, &pos_out, &ok_val)) { pos335 = pos_out; result337 = ok_val; goto label336; } else goto label338; }
 label338:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos332, end, &pos_out, &ok_val)) { pos339 = pos_out; result341 = ok_val; goto label340; } else goto fail; }
 label340:
  pos335 = pos339;
  { void *c = result334; result337 = 0; }
  goto label336;
 label336:
  pos_out1 = pos335;
  { void *rest = result337; void *c = result334; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname_aux3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos357;
  void *result359;
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux1(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto label356; }
 label356:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos357 = pos_out; result359 = ok_val; goto label358; } else goto fail; }
 label358:
  pos_out1 = pos357;
  { ok_val1 = mk_glob_path_end(r, 1 /* slash */); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname_aux2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos364;
  void *result366;
  const char *pos367;
  void *result369;
  const char *pos361;
  void *result363;
  { const char *pos_out; void *ok_val; if(f_tmp1(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos364 = pos_out; result366 = ok_val; goto label365; } else goto label360; }
 label365:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux3(err_pos, r, pos364, end, &pos_out, &ok_val)) { pos367 = pos_out; result369 = ok_val; goto label368; } else goto label360; }
 label368:
  pos_out1 = pos367;
  { void *x = result369; ok_val1 = x; }
  goto ok;
 label360:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos361 = pos_out; result363 = ok_val; goto label362; } else goto fail; }
 label362:
  pos_out1 = pos361;
  { ok_val1 = mk_glob_path_end(r, 0 /* slash */); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos370;
  void *result372;
  const char *pos373;
  void *result375;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '/') { pos370 = pos_in1 + 1; result372 = 0; goto label371; } else goto fail;
 label371:
  { const char *pos_out; void *ok_val; if(f_tmp1(err_pos, r, pos370, end, &pos_out, &ok_val)) { pos373 = pos_out; result375 = ok_val; goto label374; } else goto label376; }
 label376:
  pos373 = pos370;
  { void *x = result372; result375 = 0; }
  goto label374;
 label374:
  pos_out1 = pos373;
  { void *xs = result375; void *x = result372; ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname_aux1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos377;
  void *result379;
  const char *pos380;
  void *result382;
  { const char *pos_out; void *ok_val; if(f_glob_leafname(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos377 = pos_out; result379 = ok_val; goto label378; } else goto fail; }
 label378:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux2(err_pos, r, pos377, end, &pos_out, &ok_val)) { pos380 = pos_out; result382 = ok_val; goto label381; } else goto fail; }
 label381:
  pos_out1 = pos380;
  { void *rest = result382; void *name = result379; ok_val1 = mk_glob_path_cons(r, name, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos383;
  void *result385;
  const char *junk_pos416;
  const char *junk_pos417;
  const char *junk_pos419;
  const char *junk_pos420;
  const char *pos386;
  void *result388;
  const char *pos410;
  void *result412;
  const char *pos413;
  void *result415;
  const char *pos397;
  void *result399;
  const char *pos400;
  void *result402;
  const char *pos407;
  void *result409;
  const char *pos403;
  void *result405;
  const char *pos394;
  void *result396;
  const char *pos389;
  void *result391;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_' || *pos_in1 == '/' || *pos_in1 == '.' || *pos_in1 == '~' || *pos_in1 == '*')) { junk_pos419 = pos_in1 + 1; junk_pos420 = (void*) (int) *pos_in1; goto label418; } else goto label421;
 label421:
  junk_pos416 = pos_in1; junk_pos417 = 0; goto fail;
 label418:
  pos383 = pos_in1; result385 = 0; goto label384;
 label384:
  { const char *pos_out; void *ok_val; if(f_tmp0(err_pos, r, pos383, end, &pos_out, &ok_val)) { pos410 = pos_out; result412 = ok_val; goto label411; } else goto label392; }
 label411:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux3(err_pos, r, pos410, end, &pos_out, &ok_val)) { pos413 = pos_out; result415 = ok_val; goto label414; } else goto label392; }
 label414:
  pos386 = pos413;
  { void *p = result415; result388 = mk_glob_path(r, mk_start_root(r), p); }
  goto label387;
 label392:
  if(*err_pos < pos383) *err_pos = pos383;
  if(pos383 < end && *pos383 == '~') { pos397 = pos383 + 1; result399 = 0; goto label398; } else goto label393;
 label398:
  { const char *pos_out; void *ok_val; if(f_user_name(err_pos, r, pos397, end, &pos_out, &ok_val)) { pos400 = pos_out; result402 = ok_val; goto label401; } else goto label406; }
 label406:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos397, end, &pos_out, &ok_val)) { pos407 = pos_out; result409 = ok_val; goto label408; } else goto label393; }
 label408:
  pos400 = pos407;
  { result402 = 0; }
  goto label401;
 label401:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux2(err_pos, r, pos400, end, &pos_out, &ok_val)) { pos403 = pos_out; result405 = ok_val; goto label404; } else goto label393; }
 label404:
  pos386 = pos403;
  { void *p = result405; void *user = result402; result388 = mk_glob_path(r, mk_start_home(r, user), p); }
  goto label387;
 label393:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux1(err_pos, r, pos383, end, &pos_out, &ok_val)) { pos394 = pos_out; result396 = ok_val; goto label395; } else goto fail; }
 label395:
  pos386 = pos394;
  { void *p = result396; result388 = mk_glob_path(r, mk_start_cwd(r), p); }
  goto label387;
 label387:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos386, end, &pos_out, &ok_val)) { pos389 = pos_out; result391 = ok_val; goto label390; } else goto fail; }
 label390:
  pos_out1 = pos389;
  { void *p = result388; ok_val1 = p; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp0(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos422;
  void *result424;
  const char *pos425;
  void *result427;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && *pos_in1 == '/') { pos422 = pos_in1 + 1; result424 = 0; goto label423; } else goto fail;
 label423:
  { const char *pos_out; void *ok_val; if(f_tmp0(err_pos, r, pos422, end, &pos_out, &ok_val)) { pos425 = pos_out; result427 = ok_val; goto label426; } else goto label428; }
 label428:
  pos425 = pos422;
  { void *x = result424; result427 = 0; }
  goto label426;
 label426:
  pos_out1 = pos425;
  { void *xs = result427; void *x = result424; ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname_aux(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos429;
  void *result431;
  const char *pos439;
  void *result441;
  const char *junk_pos445;
  const char *junk_pos446;
  const char *pos442;
  void *result444;
  const char *pos432;
  void *result434;
  const char *pos436;
  void *result438;
  { const char *pos_out; void *ok_val; if(f_wschar(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { junk_pos445 = pos_out; junk_pos446 = ok_val; goto fail; } else goto label448; }
 label448:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (*pos_in1 == '&' || *pos_in1 == '|' || *pos_in1 == '*' || *pos_in1 == '=' || *pos_in1 == '{' || *pos_in1 == '}' || *pos_in1 == '(' || *pos_in1 == ')')) { junk_pos445 = pos_in1 + 1; junk_pos446 = (void*) (int) *pos_in1; goto fail; } else goto label447;
 label447:
  pos439 = pos_in1; result441 = 0; goto label440;
 label440:
  { const char *pos_out; void *ok_val; if(f_char(err_pos, r, pos439, end, &pos_out, &ok_val)) { pos442 = pos_out; result444 = ok_val; goto label443; } else goto fail; }
 label443:
  pos429 = pos442;
  { void *c = result444; result431 = (void*) c; }
  goto label430;
 label430:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(err_pos, r, pos429, end, &pos_out, &ok_val)) { pos432 = pos_out; result434 = ok_val; goto label433; } else goto label435; }
 label435:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos429, end, &pos_out, &ok_val)) { pos436 = pos_out; result438 = ok_val; goto label437; } else goto fail; }
 label437:
  pos432 = pos436;
  { void *c = result431; result434 = 0; }
  goto label433;
 label433:
  pos_out1 = pos432;
  { void *rest = result434; void *c = result431; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos449;
  void *result451;
  const char *junk_pos458;
  const char *junk_pos459;
  const char *junk_pos461;
  const char *junk_pos462;
  const char *pos452;
  void *result454;
  const char *pos455;
  void *result457;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_' || *pos_in1 == '/' || *pos_in1 == '.' || *pos_in1 == '~')) { junk_pos461 = pos_in1 + 1; junk_pos462 = (void*) (int) *pos_in1; goto label460; } else goto label463;
 label463:
  junk_pos458 = pos_in1; junk_pos459 = 0; goto fail;
 label460:
  pos449 = pos_in1; result451 = 0; goto label450;
 label450:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(err_pos, r, pos449, end, &pos_out, &ok_val)) { pos452 = pos_out; result454 = ok_val; goto label453; } else goto fail; }
 label453:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos452, end, &pos_out, &ok_val)) { pos455 = pos_out; result457 = ok_val; goto label456; } else goto fail; }
 label456:
  pos_out1 = pos455;
  { void *s = result454; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_redirection(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos464;
  void *result466;
  const char *pos508;
  void *result510;
  const char *pos511;
  void *result513;
  const char *pos505;
  void *result507;
  const char *pos467;
  void *result469;
  const char *pos501;
  void *result503;
  const char *pos498;
  void *result500;
  const char *pos495;
  void *result497;
  const char *pos492;
  void *result494;
  const char *pos470;
  void *result472;
  const char *pos473;
  void *result475;
  const char *pos480;
  void *result482;
  const char *pos483;
  void *result485;
  const char *pos486;
  void *result488;
  const char *pos477;
  void *result479;
  { const char *pos_out; void *ok_val; if(f_number(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos508 = pos_out; result510 = ok_val; goto label509; } else goto label504; }
 label509:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos508, end, &pos_out, &ok_val)) { pos511 = pos_out; result513 = ok_val; goto label512; } else goto label504; }
 label512:
  pos464 = pos511;
  { void *n = result510; result466 = n; }
  goto label465;
 label504:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos505 = pos_out; result507 = ok_val; goto label506; } else goto fail; }
 label506:
  pos464 = pos505;
  { result466 = 0; }
  goto label465;
 label465:
  if(*err_pos < pos464) *err_pos = pos464;
  if(pos464 + 2 <= end && pos464[0] == '>' && pos464[1] == '>') { pos501 = pos464 + 2; result503 = 0; goto label502; } else goto label489;
 label502:
  pos467 = pos501;
  { void *fd = result466; result469 = (void *) REDIR_OUT_APPEND; }
  goto label468;
 label489:
  if(*err_pos < pos464) *err_pos = pos464;
  if(pos464 + 1 <= end && pos464[0] == '>') { pos498 = pos464 + 1; result500 = 0; goto label499; } else goto label490;
 label499:
  pos467 = pos498;
  { void *fd = result466; result469 = (void *) REDIR_OUT_TRUNC; }
  goto label468;
 label490:
  if(*err_pos < pos464) *err_pos = pos464;
  if(pos464 + 2 <= end && pos464[0] == '<' && pos464[1] == '>') { pos495 = pos464 + 2; result497 = 0; goto label496; } else goto label491;
 label496:
  pos467 = pos495;
  { void *fd = result466; result469 = (void *) REDIR_IN_OUT; }
  goto label468;
 label491:
  if(*err_pos < pos464) *err_pos = pos464;
  if(pos464 + 1 <= end && pos464[0] == '<') { pos492 = pos464 + 1; result494 = 0; goto label493; } else goto fail;
 label493:
  pos467 = pos492;
  { void *fd = result466; result469 = (void *) REDIR_IN; }
  goto label468;
 label468:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos467, end, &pos_out, &ok_val)) { pos470 = pos_out; result472 = ok_val; goto label471; } else goto fail; }
 label471:
  if(*err_pos < pos470) *err_pos = pos470;
  if(pos470 < end && *pos470 == '&') { pos480 = pos470 + 1; result482 = 0; goto label481; } else goto label476;
 label481:
  { const char *pos_out; void *ok_val; if(f_number(err_pos, r, pos480, end, &pos_out, &ok_val)) { pos483 = pos_out; result485 = ok_val; goto label484; } else goto label476; }
 label484:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos483, end, &pos_out, &ok_val)) { pos486 = pos_out; result488 = ok_val; goto label487; } else goto label476; }
 label487:
  pos473 = pos486;
  { void *n = result485; void *type = result469; void *fd = result466; result475 = mk_dest_fd(r, n); }
  goto label474;
 label476:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos470, end, &pos_out, &ok_val)) { pos477 = pos_out; result479 = ok_val; goto label478; } else goto fail; }
 label478:
  pos473 = pos477;
  { void *p = result479; void *type = result469; void *fd = result466; result475 = mk_dest_file(r, p); }
  goto label474;
 label474:
  pos_out1 = pos473;
  { void *dest = result475; void *type = result469; void *fd = result466; ok_val1 = mk_arg_redirection(r, fd, (int) type, dest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arg(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos533;
  void *result535;
  const char *pos530;
  void *result532;
  const char *pos521;
  void *result523;
  const char *pos524;
  void *result526;
  const char *pos527;
  void *result529;
  const char *pos518;
  void *result520;
  { const char *pos_out; void *ok_val; if(f_option(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos533 = pos_out; result535 = ok_val; goto label534; } else goto label514; }
 label534:
  pos_out1 = pos533;
  { void *s = result535; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label514:
  { const char *pos_out; void *ok_val; if(f_string_literal(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos530 = pos_out; result532 = ok_val; goto label531; } else goto label515; }
 label531:
  pos_out1 = pos530;
  { void *s = result532; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label515:
  { const char *pos_out; void *ok_val; if(f_redirection(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto label516; }
 label516:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos521 = pos_out; result523 = ok_val; goto label522; } else goto label517; }
 label522:
  { const char *pos_out; void *ok_val; if(f_equals(err_pos, r, pos521, end, &pos_out, &ok_val)) { pos524 = pos_out; result526 = ok_val; goto label525; } else goto label517; }
 label525:
  { const char *pos_out; void *ok_val; if(f_expr2(err_pos, r, pos524, end, &pos_out, &ok_val)) { pos527 = pos_out; result529 = ok_val; goto label528; } else goto label517; }
 label528:
  pos_out1 = pos527;
  { void *e = result529; void *f = result523; ok_val1 = mk_arg_fs_binding(r, f, e); }
  goto ok;
 label517:
  { const char *pos_out; void *ok_val; if(f_glob_pathname(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos518 = pos_out; result520 = ok_val; goto label519; } else goto fail; }
 label519:
  pos_out1 = pos518;
  { void *f = result520; ok_val1 = mk_arg_glob_filename(r, f); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist4(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos537;
  void *result539;
  const char *pos540;
  void *result542;
  const char *pos543;
  void *result545;
  { const char *pos_out; void *ok_val; if(f_c_open(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos537 = pos_out; result539 = ok_val; goto label538; } else goto label536; }
 label538:
  { const char *pos_out; void *ok_val; if(f_arglist1(err_pos, r, pos537, end, &pos_out, &ok_val)) { pos540 = pos_out; result542 = ok_val; goto label541; } else goto label536; }
 label541:
  { const char *pos_out; void *ok_val; if(f_c_close(err_pos, r, pos540, end, &pos_out, &ok_val)) { pos543 = pos_out; result545 = ok_val; goto label544; } else goto label536; }
 label544:
  pos_out1 = pos543;
  { void *l = result542; ok_val1 = l; }
  goto ok;
 label536:
  { const char *pos_out; void *ok_val; if(f_arg(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist3(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos550;
  void *result552;
  const char *pos553;
  void *result555;
  const char *pos547;
  void *result549;
  { const char *pos_out; void *ok_val; if(f_arglist4(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos550 = pos_out; result552 = ok_val; goto label551; } else goto label546; }
 label551:
  { const char *pos_out; void *ok_val; if(f_arglist3(err_pos, r, pos550, end, &pos_out, &ok_val)) { pos553 = pos_out; result555 = ok_val; goto label554; } else goto label546; }
 label554:
  pos_out1 = pos553;
  { void *a2 = result555; void *a1 = result552; ok_val1 = mk_arg_cat(r, a1, a2); }
  goto ok;
 label546:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos547 = pos_out; result549 = ok_val; goto label548; } else goto fail; }
 label548:
  pos_out1 = pos547;
  { ok_val1 = mk_arg_empty(r); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist2(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos557;
  void *result559;
  const char *pos560;
  void *result562;
  const char *pos563;
  void *result565;
  { const char *pos_out; void *ok_val; if(f_arglist3(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos557 = pos_out; result559 = ok_val; goto label558; } else goto label556; }
 label558:
  { const char *pos_out; void *ok_val; if(f_plus(err_pos, r, pos557, end, &pos_out, &ok_val)) { pos560 = pos_out; result562 = ok_val; goto label561; } else goto label556; }
 label561:
  { const char *pos_out; void *ok_val; if(f_arglist2(err_pos, r, pos560, end, &pos_out, &ok_val)) { pos563 = pos_out; result565 = ok_val; goto label564; } else goto label556; }
 label564:
  pos_out1 = pos563;
  { void *fs = result565; void *a = result559; ok_val1 = mk_arg_cat(r, a, mk_arg_ambient(r, fs)); }
  goto ok;
 label556:
  { const char *pos_out; void *ok_val; if(f_arglist3(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist1(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos567;
  void *result569;
  const char *pos570;
  void *result572;
  const char *pos573;
  void *result575;
  { const char *pos_out; void *ok_val; if(f_arglist2(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos567 = pos_out; result569 = ok_val; goto label568; } else goto label566; }
 label568:
  { const char *pos_out; void *ok_val; if(f_arrow(err_pos, r, pos567, end, &pos_out, &ok_val)) { pos570 = pos_out; result572 = ok_val; goto label571; } else goto label566; }
 label571:
  { const char *pos_out; void *ok_val; if(f_arglist2(err_pos, r, pos570, end, &pos_out, &ok_val)) { pos573 = pos_out; result575 = ok_val; goto label574; } else goto label566; }
 label574:
  pos_out1 = pos573;
  { void *a2 = result575; void *a1 = result569; ok_val1 = mk_arg_cat(r, mk_arg_read(r, a1), mk_arg_write(r, a2)); }
  goto ok;
 label566:
  { const char *pos_out; void *ok_val; if(f_arglist2(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_invocation(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos576;
  void *result578;
  const char *pos589;
  void *result591;
  const char *pos586;
  void *result588;
  const char *pos579;
  void *result581;
  const char *pos582;
  void *result584;
  { const char *pos_out; void *ok_val; if(f_bang_bang(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos589 = pos_out; result591 = ok_val; goto label590; } else goto label585; }
 label590:
  pos576 = pos589;
  { result578 = (void *) 1; }
  goto label577;
 label585:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos586 = pos_out; result588 = ok_val; goto label587; } else goto fail; }
 label587:
  pos576 = pos586;
  { result578 = 0; }
  goto label577;
 label577:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos576, end, &pos_out, &ok_val)) { pos579 = pos_out; result581 = ok_val; goto label580; } else goto fail; }
 label580:
  { const char *pos_out; void *ok_val; if(f_arglist1(err_pos, r, pos579, end, &pos_out, &ok_val)) { pos582 = pos_out; result584 = ok_val; goto label583; } else goto fail; }
 label583:
  pos_out1 = pos582;
  { void *args = result584; void *cmd = result581; void *no_sec = result578; ok_val1 = mk_invocation(r, (int) no_sec, cmd, args); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pipeline(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos596;
  void *result598;
  const char *pos599;
  void *result601;
  const char *pos602;
  void *result604;
  const char *pos593;
  void *result595;
  { const char *pos_out; void *ok_val; if(f_invocation(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos596 = pos_out; result598 = ok_val; goto label597; } else goto label592; }
 label597:
  { const char *pos_out; void *ok_val; if(f_pipe_bar(err_pos, r, pos596, end, &pos_out, &ok_val)) { pos599 = pos_out; result601 = ok_val; goto label600; } else goto label592; }
 label600:
  { const char *pos_out; void *ok_val; if(f_pipeline(err_pos, r, pos599, end, &pos_out, &ok_val)) { pos602 = pos_out; result604 = ok_val; goto label603; } else goto label592; }
 label603:
  pos_out1 = pos602;
  { void *pl = result604; void *inv = result598; ok_val1 = mk_pipeline_cons(r, inv, pl); }
  goto ok;
 label592:
  { const char *pos_out; void *ok_val; if(f_invocation(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos593 = pos_out; result595 = ok_val; goto label594; } else goto fail; }
 label594:
  pos_out1 = pos593;
  { void *inv = result595; ok_val1 = mk_pipeline_inv(r, inv); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_command(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos674;
  void *result676;
  const char *pos677;
  void *result679;
  const char *pos680;
  void *result682;
  const char *pos668;
  void *result670;
  const char *pos671;
  void *result673;
  const char *pos656;
  void *result658;
  const char *pos659;
  void *result661;
  const char *pos662;
  void *result664;
  const char *pos665;
  void *result667;
  const char *pos644;
  void *result646;
  const char *pos647;
  void *result649;
  const char *pos650;
  void *result652;
  const char *pos653;
  void *result655;
  const char *pos623;
  void *result625;
  const char *pos626;
  void *result628;
  const char *junk_pos641;
  const char *junk_pos642;
  const char *pos629;
  void *result631;
  const char *pos632;
  void *result634;
  const char *pos635;
  void *result637;
  const char *pos638;
  void *result640;
  const char *pos610;
  void *result612;
  const char *pos613;
  void *result615;
  const char *pos620;
  void *result622;
  const char *pos617;
  void *result619;
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos674 = pos_in1 + 2; result676 = 0; goto label675; } else goto label605;
 label675:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos674, end, &pos_out, &ok_val)) { pos677 = pos_out; result679 = ok_val; goto label678; } else goto label605; }
 label678:
  { const char *pos_out; void *ok_val; if(f_pathname(err_pos, r, pos677, end, &pos_out, &ok_val)) { pos680 = pos_out; result682 = ok_val; goto label681; } else goto label605; }
 label681:
  pos_out1 = pos680;
  { void *dir = result682; ok_val1 = mk_chdir(r, dir); }
  goto ok;
 label605:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos668 = pos_in1 + 2; result670 = 0; goto label669; } else goto label606;
 label669:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos668, end, &pos_out, &ok_val)) { pos671 = pos_out; result673 = ok_val; goto label672; } else goto label606; }
 label672:
  pos_out1 = pos671;
  { ok_val1 = mk_chdir(r, char_cons(r, '~', 0)); }
  goto ok;
 label606:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'f' && pos_in1[1] == 'g') { pos656 = pos_in1 + 2; result658 = 0; goto label657; } else goto label607;
 label657:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos656, end, &pos_out, &ok_val)) { pos659 = pos_out; result661 = ok_val; goto label660; } else goto label607; }
 label660:
  { const char *pos_out; void *ok_val; if(f_number(err_pos, r, pos659, end, &pos_out, &ok_val)) { pos662 = pos_out; result664 = ok_val; goto label663; } else goto label607; }
 label663:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos662, end, &pos_out, &ok_val)) { pos665 = pos_out; result667 = ok_val; goto label666; } else goto label607; }
 label666:
  pos_out1 = pos665;
  { void *n = result664; ok_val1 = mk_command_fg(r, n); }
  goto ok;
 label607:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'b' && pos_in1[1] == 'g') { pos644 = pos_in1 + 2; result646 = 0; goto label645; } else goto label608;
 label645:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos644, end, &pos_out, &ok_val)) { pos647 = pos_out; result649 = ok_val; goto label648; } else goto label608; }
 label648:
  { const char *pos_out; void *ok_val; if(f_number(err_pos, r, pos647, end, &pos_out, &ok_val)) { pos650 = pos_out; result652 = ok_val; goto label651; } else goto label608; }
 label651:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos650, end, &pos_out, &ok_val)) { pos653 = pos_out; result655 = ok_val; goto label654; } else goto label608; }
 label654:
  pos_out1 = pos653;
  { void *n = result652; ok_val1 = mk_command_bg(r, n); }
  goto ok;
 label608:
  if(*err_pos < pos_in1) *err_pos = pos_in1;
  if(pos_in1 + 3 <= end && pos_in1[0] == 'd' && pos_in1[1] == 'e' && pos_in1[2] == 'f') { pos623 = pos_in1 + 3; result625 = 0; goto label624; } else goto label609;
 label624:
  if(*err_pos < pos623) *err_pos = pos623;
  if(pos623 < end && (('a' <= *pos623 && *pos623 <= 'z') || ('A' <= *pos623 && *pos623 <= 'Z') || ('0' <= *pos623 && *pos623 <= '9') || *pos623 == '_')) { junk_pos641 = pos623 + 1; junk_pos642 = (void*) (int) *pos623; goto label609; } else goto label643;
 label643:
  pos626 = pos623; result628 = 0; goto label627;
 label627:
  { const char *pos_out; void *ok_val; if(f_ws(err_pos, r, pos626, end, &pos_out, &ok_val)) { pos629 = pos_out; result631 = ok_val; goto label630; } else goto label609; }
 label630:
  { const char *pos_out; void *ok_val; if(f_var_name(err_pos, r, pos629, end, &pos_out, &ok_val)) { pos632 = pos_out; result634 = ok_val; goto label633; } else goto label609; }
 label633:
  { const char *pos_out; void *ok_val; if(f_equals(err_pos, r, pos632, end, &pos_out, &ok_val)) { pos635 = pos_out; result637 = ok_val; goto label636; } else goto label609; }
 label636:
  { const char *pos_out; void *ok_val; if(f_expr1(err_pos, r, pos635, end, &pos_out, &ok_val)) { pos638 = pos_out; result640 = ok_val; goto label639; } else goto label609; }
 label639:
  pos_out1 = pos638;
  { void *e = result640; void *var = result634; ok_val1 = mk_def_binding(r, var, e); }
  goto ok;
 label609:
  { const char *pos_out; void *ok_val; if(f_pipeline(err_pos, r, pos_in1, end, &pos_out, &ok_val)) { pos610 = pos_out; result612 = ok_val; goto label611; } else goto fail; }
 label611:
  { const char *pos_out; void *ok_val; if(f_ampersand(err_pos, r, pos610, end, &pos_out, &ok_val)) { pos620 = pos_out; result622 = ok_val; goto label621; } else goto label616; }
 label621:
  pos613 = pos620;
  { void *cmd = result612; result615 = (void *) 1; }
  goto label614;
 label616:
  { const char *pos_out; void *ok_val; if(f_null(err_pos, r, pos610, end, &pos_out, &ok_val)) { pos617 = pos_out; result619 = ok_val; goto label618; } else goto fail; }
 label618:
  pos613 = pos617;
  { void *cmd = result612; result615 = 0; }
  goto label614;
 label614:
  pos_out1 = pos613;
  { void *bg_flag = result615; void *cmd = result612; ok_val1 = mk_command(r, cmd, (int) bg_flag); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_fail(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_null(const char **err_pos, region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  pos_out1 = pos_in1;
  ok_val1 = 0;
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}
