/* This file is automatically generated from shell.gram */
#include "region.h"
#include "shell.h"
#include "shell-variants.h"
/* This file is automatically generated */


int f_wschar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ws(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp0(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_tmp1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_bang_bang(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pipe_bar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_ampersand(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_plus(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arrow(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_close(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_c_open(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_number(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_char(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_opt_str(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_option(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_str_lit1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_string_literal(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_glob_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arg(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist4(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist3(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_arglist1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_invocation(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_pipeline(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_command(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_fail(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);
int f_null(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p);

int f_wschar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  if(pos_in1 < end && *pos_in1 == ' ') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label0;
 label0:
  if(pos_in1 < end && *pos_in1 == '\t') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto label1;
 label1:
  if(pos_in1 < end && *pos_in1 == '\n') { pos_out1 = pos_in1 + 1; ok_val1 = 0; goto ok; } else goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ws(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  { const char *pos_out; void *ok_val; if(f_tmp0(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp0(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos3;
  void *result5;
  const char *pos10;
  void *result12;
  const char *pos13;
  void *result15;
  const char *pos16;
  void *result18;
  const char *pos6;
  void *result8;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { pos3 = pos_out; result5 = ok_val; goto label4; } else goto label9; }
 label9:
  if(pos_in1 < end && *pos_in1 == '#') { pos10 = pos_in1 + 1; result12 = 0; goto label11; } else goto label2;
 label11:
  { const char *pos_out; void *ok_val; if(f_tmp1(r, pos10, end, &pos_out, &ok_val)) { pos13 = pos_out; result15 = ok_val; goto label14; } else goto label2; }
 label14:
  if(pos13 < end && *pos13 == '\n') { pos16 = pos13 + 1; result18 = 0; goto label17; } else goto label2;
 label17:
  pos3 = pos16;
  { result5 = 0; }
  goto label4;
 label4:
  { const char *pos_out; void *ok_val; if(f_tmp0(r, pos3, end, &pos_out, &ok_val)) { pos6 = pos_out; result8 = ok_val; goto label7; } else goto label2; }
 label7:
  pos_out1 = pos6;
  { void *xs = result8; void *x = result5; ok_val1 = 0; }
  goto ok;
 label2:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_tmp1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos20;
  void *result22;
  const char *pos26;
  void *result28;
  const char *junk_pos32;
  const char *junk_pos33;
  const char *pos29;
  void *result31;
  const char *pos23;
  void *result25;
  if(pos_in1 < end && *pos_in1 == '\n') { junk_pos32 = pos_in1 + 1; junk_pos33 = 0; goto label19; } else goto label34;
 label34:
  pos26 = pos_in1; result28 = 0; goto label27;
 label27:
  if(pos26 < end) { pos29 = pos26 + 1; result31 = (void*) *pos26; goto label30; } else goto label19;
 label30:
  pos20 = pos29;
  { result22 = 0; }
  goto label21;
 label21:
  { const char *pos_out; void *ok_val; if(f_tmp1(r, pos20, end, &pos_out, &ok_val)) { pos23 = pos_out; result25 = ok_val; goto label24; } else goto label19; }
 label24:
  pos_out1 = pos23;
  { void *xs = result25; void *x = result22; ok_val1 = 0; }
  goto ok;
 label19:
  pos_out1 = pos_in1;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_bang_bang(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos35;
  void *result37;
  const char *pos38;
  void *result40;
  if(pos_in1 + 2 <= end && pos_in1[0] == '!' && pos_in1[1] == '!') { pos35 = pos_in1 + 2; result37 = 0; goto label36; } else goto fail;
 label36:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos35, end, &pos_out, &ok_val)) { pos38 = pos_out; result40 = ok_val; goto label39; } else goto fail; }
 label39:
  pos_out1 = pos38;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pipe_bar(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos41;
  void *result43;
  const char *pos44;
  void *result46;
  if(pos_in1 < end && *pos_in1 == '|') { pos41 = pos_in1 + 1; result43 = 0; goto label42; } else goto fail;
 label42:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos41, end, &pos_out, &ok_val)) { pos44 = pos_out; result46 = ok_val; goto label45; } else goto fail; }
 label45:
  pos_out1 = pos44;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_ampersand(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos47;
  void *result49;
  const char *pos50;
  void *result52;
  if(pos_in1 < end && *pos_in1 == '&') { pos47 = pos_in1 + 1; result49 = 0; goto label48; } else goto fail;
 label48:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos47, end, &pos_out, &ok_val)) { pos50 = pos_out; result52 = ok_val; goto label51; } else goto fail; }
 label51:
  pos_out1 = pos50;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_plus(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos53;
  void *result55;
  const char *pos56;
  void *result58;
  if(pos_in1 < end && *pos_in1 == '+') { pos53 = pos_in1 + 1; result55 = 0; goto label54; } else goto fail;
 label54:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos53, end, &pos_out, &ok_val)) { pos56 = pos_out; result58 = ok_val; goto label57; } else goto fail; }
 label57:
  pos_out1 = pos56;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arrow(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos59;
  void *result61;
  const char *pos62;
  void *result64;
  if(pos_in1 + 2 <= end && pos_in1[0] == '=' && pos_in1[1] == '>') { pos59 = pos_in1 + 2; result61 = 0; goto label60; } else goto fail;
 label60:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos59, end, &pos_out, &ok_val)) { pos62 = pos_out; result64 = ok_val; goto label63; } else goto fail; }
 label63:
  pos_out1 = pos62;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_close(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos65;
  void *result67;
  const char *pos68;
  void *result70;
  if(pos_in1 < end && *pos_in1 == '}') { pos65 = pos_in1 + 1; result67 = 0; goto label66; } else goto fail;
 label66:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos65, end, &pos_out, &ok_val)) { pos68 = pos_out; result70 = ok_val; goto label69; } else goto fail; }
 label69:
  pos_out1 = pos68;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_c_open(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos71;
  void *result73;
  const char *pos74;
  void *result76;
  if(pos_in1 < end && *pos_in1 == '{') { pos71 = pos_in1 + 1; result73 = 0; goto label72; } else goto fail;
 label72:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos71, end, &pos_out, &ok_val)) { pos74 = pos_out; result76 = ok_val; goto label75; } else goto fail; }
 label75:
  pos_out1 = pos74;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_number(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos77;
  void *result79;
  const char *pos80;
  void *result82;
  const char *pos84;
  void *result86;
  if(pos_in1 < end && (('0' <= *pos_in1 && *pos_in1 <= '9'))) { pos77 = pos_in1 + 1; result79 = (void*) *pos_in1; goto label78; } else goto fail;
 label78:
  { const char *pos_out; void *ok_val; if(f_number(r, pos77, end, &pos_out, &ok_val)) { pos80 = pos_out; result82 = ok_val; goto label81; } else goto label83; }
 label83:
  { const char *pos_out; void *ok_val; if(f_null(r, pos77, end, &pos_out, &ok_val)) { pos84 = pos_out; result86 = ok_val; goto label85; } else goto fail; }
 label85:
  pos80 = pos84;
  { void *c = result79; result82 = 0; }
  goto label81;
 label81:
  pos_out1 = pos80;
  { void *rest = result82; void *c = result79; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_char(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos138;
  void *result140;
  const char *pos141;
  void *result143;
  const char *pos132;
  void *result134;
  const char *pos135;
  void *result137;
  const char *pos126;
  void *result128;
  const char *pos129;
  void *result131;
  const char *pos120;
  void *result122;
  const char *pos123;
  void *result125;
  const char *pos114;
  void *result116;
  const char *pos117;
  void *result119;
  const char *pos108;
  void *result110;
  const char *pos111;
  void *result113;
  const char *pos93;
  void *result95;
  const char *junk_pos99;
  const char *junk_pos100;
  const char *pos102;
  void *result104;
  const char *pos105;
  void *result107;
  const char *pos96;
  void *result98;
  if(pos_in1 < end && *pos_in1 == '\\') { pos138 = pos_in1 + 1; result140 = 0; goto label139; } else goto label87;
 label139:
  if(pos138 < end && *pos138 == '\\') { pos141 = pos138 + 1; result143 = 0; goto label142; } else goto label87;
 label142:
  pos_out1 = pos141;
  { ok_val1 = (void*) '\\'; }
  goto ok;
 label87:
  if(pos_in1 < end && *pos_in1 == '\\') { pos132 = pos_in1 + 1; result134 = 0; goto label133; } else goto label88;
 label133:
  if(pos132 < end && *pos132 == '\'') { pos135 = pos132 + 1; result137 = 0; goto label136; } else goto label88;
 label136:
  pos_out1 = pos135;
  { ok_val1 = (void*) '\''; }
  goto ok;
 label88:
  if(pos_in1 < end && *pos_in1 == '\\') { pos126 = pos_in1 + 1; result128 = 0; goto label127; } else goto label89;
 label127:
  if(pos126 < end && *pos126 == '"') { pos129 = pos126 + 1; result131 = 0; goto label130; } else goto label89;
 label130:
  pos_out1 = pos129;
  { ok_val1 = (void*) '"'; }
  goto ok;
 label89:
  if(pos_in1 < end && *pos_in1 == '\\') { pos120 = pos_in1 + 1; result122 = 0; goto label121; } else goto label90;
 label121:
  if(pos120 < end && *pos120 == ' ') { pos123 = pos120 + 1; result125 = 0; goto label124; } else goto label90;
 label124:
  pos_out1 = pos123;
  { ok_val1 = (void*) ' '; }
  goto ok;
 label90:
  if(pos_in1 < end && *pos_in1 == '\\') { pos114 = pos_in1 + 1; result116 = 0; goto label115; } else goto label91;
 label115:
  if(pos114 < end && *pos114 == 'n') { pos117 = pos114 + 1; result119 = 0; goto label118; } else goto label91;
 label118:
  pos_out1 = pos117;
  { ok_val1 = (void*) '\n'; }
  goto ok;
 label91:
  if(pos_in1 < end && *pos_in1 == '\\') { pos108 = pos_in1 + 1; result110 = 0; goto label109; } else goto label92;
 label109:
  if(pos108 < end && *pos108 == 't') { pos111 = pos108 + 1; result113 = 0; goto label112; } else goto label92;
 label112:
  pos_out1 = pos111;
  { ok_val1 = (void*) '\t'; }
  goto ok;
 label92:
  if(pos_in1 < end && *pos_in1 == '\\') { pos102 = pos_in1 + 1; result104 = 0; goto label103; } else goto label101;
 label103:
  if(pos102 < end) { pos105 = pos102 + 1; result107 = (void*) *pos102; goto label106; } else goto label101;
 label106:
  junk_pos99 = pos105;
  { junk_pos100 = 0; }
  goto fail;
 label101:
  pos93 = pos_in1; result95 = 0; goto label94;
 label94:
  if(pos93 < end) { pos96 = pos93 + 1; result98 = (void*) *pos93; goto label97; } else goto fail;
 label97:
  pos_out1 = pos96;
  { void *c = result98; ok_val1 = (void*) c; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_opt_str(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos148;
  void *result150;
  const char *junk_pos157;
  const char *junk_pos158;
  const char *pos151;
  void *result153;
  const char *pos154;
  void *result156;
  const char *pos145;
  void *result147;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { junk_pos157 = pos_out; junk_pos158 = ok_val; goto label144; } else goto label159; }
 label159:
  pos148 = pos_in1; result150 = 0; goto label149;
 label149:
  { const char *pos_out; void *ok_val; if(f_char(r, pos148, end, &pos_out, &ok_val)) { pos151 = pos_out; result153 = ok_val; goto label152; } else goto label144; }
 label152:
  { const char *pos_out; void *ok_val; if(f_opt_str(r, pos151, end, &pos_out, &ok_val)) { pos154 = pos_out; result156 = ok_val; goto label155; } else goto label144; }
 label155:
  pos_out1 = pos154;
  { void *rest = result156; void *c = result153; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label144:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos145 = pos_out; result147 = ok_val; goto label146; } else goto fail; }
 label146:
  pos_out1 = pos145;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_option(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos160;
  void *result162;
  const char *pos163;
  void *result165;
  const char *pos166;
  void *result168;
  if(pos_in1 < end && *pos_in1 == '-') { pos160 = pos_in1 + 1; result162 = 0; goto label161; } else goto fail;
 label161:
  { const char *pos_out; void *ok_val; if(f_opt_str(r, pos160, end, &pos_out, &ok_val)) { pos163 = pos_out; result165 = ok_val; goto label164; } else goto fail; }
 label164:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos163, end, &pos_out, &ok_val)) { pos166 = pos_out; result168 = ok_val; goto label167; } else goto fail; }
 label167:
  pos_out1 = pos166;
  { void *s = result165; ok_val1 = char_cons(r, '-', s); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos173;
  void *result175;
  const char *junk_pos182;
  const char *junk_pos183;
  const char *pos176;
  void *result178;
  const char *pos179;
  void *result181;
  const char *pos170;
  void *result172;
  if(pos_in1 < end && *pos_in1 == '\'') { junk_pos182 = pos_in1 + 1; junk_pos183 = 0; goto label169; } else goto label184;
 label184:
  pos173 = pos_in1; result175 = 0; goto label174;
 label174:
  { const char *pos_out; void *ok_val; if(f_char(r, pos173, end, &pos_out, &ok_val)) { pos176 = pos_out; result178 = ok_val; goto label177; } else goto label169; }
 label177:
  { const char *pos_out; void *ok_val; if(f_str_lit2(r, pos176, end, &pos_out, &ok_val)) { pos179 = pos_out; result181 = ok_val; goto label180; } else goto label169; }
 label180:
  pos_out1 = pos179;
  { void *rest = result181; void *c = result178; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label169:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos170 = pos_out; result172 = ok_val; goto label171; } else goto fail; }
 label171:
  pos_out1 = pos170;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_str_lit1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos189;
  void *result191;
  const char *junk_pos198;
  const char *junk_pos199;
  const char *pos192;
  void *result194;
  const char *pos195;
  void *result197;
  const char *pos186;
  void *result188;
  if(pos_in1 < end && *pos_in1 == '"') { junk_pos198 = pos_in1 + 1; junk_pos199 = 0; goto label185; } else goto label200;
 label200:
  pos189 = pos_in1; result191 = 0; goto label190;
 label190:
  { const char *pos_out; void *ok_val; if(f_char(r, pos189, end, &pos_out, &ok_val)) { pos192 = pos_out; result194 = ok_val; goto label193; } else goto label185; }
 label193:
  { const char *pos_out; void *ok_val; if(f_str_lit1(r, pos192, end, &pos_out, &ok_val)) { pos195 = pos_out; result197 = ok_val; goto label196; } else goto label185; }
 label196:
  pos_out1 = pos195;
  { void *rest = result197; void *c = result194; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 label185:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos186 = pos_out; result188 = ok_val; goto label187; } else goto fail; }
 label187:
  pos_out1 = pos186;
  { ok_val1 = 0; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_string_literal(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos214;
  void *result216;
  const char *pos217;
  void *result219;
  const char *pos220;
  void *result222;
  const char *pos223;
  void *result225;
  const char *pos202;
  void *result204;
  const char *pos205;
  void *result207;
  const char *pos208;
  void *result210;
  const char *pos211;
  void *result213;
  if(pos_in1 < end && *pos_in1 == '"') { pos214 = pos_in1 + 1; result216 = 0; goto label215; } else goto label201;
 label215:
  { const char *pos_out; void *ok_val; if(f_str_lit1(r, pos214, end, &pos_out, &ok_val)) { pos217 = pos_out; result219 = ok_val; goto label218; } else goto label201; }
 label218:
  if(pos217 < end && *pos217 == '"') { pos220 = pos217 + 1; result222 = 0; goto label221; } else goto label201;
 label221:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos220, end, &pos_out, &ok_val)) { pos223 = pos_out; result225 = ok_val; goto label224; } else goto label201; }
 label224:
  pos_out1 = pos223;
  { void *s = result219; ok_val1 = s; }
  goto ok;
 label201:
  if(pos_in1 < end && *pos_in1 == '\'') { pos202 = pos_in1 + 1; result204 = 0; goto label203; } else goto fail;
 label203:
  { const char *pos_out; void *ok_val; if(f_str_lit2(r, pos202, end, &pos_out, &ok_val)) { pos205 = pos_out; result207 = ok_val; goto label206; } else goto fail; }
 label206:
  if(pos205 < end && *pos205 == '\'') { pos208 = pos205 + 1; result210 = 0; goto label209; } else goto fail;
 label209:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos208, end, &pos_out, &ok_val)) { pos211 = pos_out; result213 = ok_val; goto label212; } else goto fail; }
 label212:
  pos_out1 = pos211;
  { void *s = result207; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos226;
  void *result228;
  const char *pos236;
  void *result238;
  const char *junk_pos242;
  const char *junk_pos243;
  const char *pos239;
  void *result241;
  const char *pos229;
  void *result231;
  const char *pos233;
  void *result235;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { junk_pos242 = pos_out; junk_pos243 = ok_val; goto fail; } else goto label245; }
 label245:
  if(pos_in1 < end && (*pos_in1 == '&' || *pos_in1 == '|')) { junk_pos242 = pos_in1 + 1; junk_pos243 = (void*) *pos_in1; goto fail; } else goto label244;
 label244:
  pos236 = pos_in1; result238 = 0; goto label237;
 label237:
  { const char *pos_out; void *ok_val; if(f_char(r, pos236, end, &pos_out, &ok_val)) { pos239 = pos_out; result241 = ok_val; goto label240; } else goto fail; }
 label240:
  pos226 = pos239;
  { void *c = result241; result228 = (void*) c; }
  goto label227;
 label227:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux(r, pos226, end, &pos_out, &ok_val)) { pos229 = pos_out; result231 = ok_val; goto label230; } else goto label232; }
 label232:
  { const char *pos_out; void *ok_val; if(f_null(r, pos226, end, &pos_out, &ok_val)) { pos233 = pos_out; result235 = ok_val; goto label234; } else goto fail; }
 label234:
  pos229 = pos233;
  { void *c = result228; result231 = 0; }
  goto label230;
 label230:
  pos_out1 = pos229;
  { void *rest = result231; void *c = result228; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_glob_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos246;
  void *result248;
  const char *junk_pos255;
  const char *junk_pos256;
  const char *junk_pos258;
  const char *junk_pos259;
  const char *pos249;
  void *result251;
  const char *pos252;
  void *result254;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_' || *pos_in1 == '/' || *pos_in1 == '.' || *pos_in1 == '~' || *pos_in1 == '*')) { junk_pos258 = pos_in1 + 1; junk_pos259 = (void*) *pos_in1; goto label257; } else goto label260;
 label260:
  junk_pos255 = pos_in1; junk_pos256 = 0; goto fail;
 label257:
  pos246 = pos_in1; result248 = 0; goto label247;
 label247:
  { const char *pos_out; void *ok_val; if(f_glob_pathname_aux(r, pos246, end, &pos_out, &ok_val)) { pos249 = pos_out; result251 = ok_val; goto label250; } else goto fail; }
 label250:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos249, end, &pos_out, &ok_val)) { pos252 = pos_out; result254 = ok_val; goto label253; } else goto fail; }
 label253:
  pos_out1 = pos252;
  { void *s = result251; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname_aux(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos261;
  void *result263;
  const char *pos271;
  void *result273;
  const char *junk_pos277;
  const char *junk_pos278;
  const char *pos274;
  void *result276;
  const char *pos264;
  void *result266;
  const char *pos268;
  void *result270;
  { const char *pos_out; void *ok_val; if(f_wschar(r, pos_in1, end, &pos_out, &ok_val)) { junk_pos277 = pos_out; junk_pos278 = ok_val; goto fail; } else goto label280; }
 label280:
  if(pos_in1 < end && (*pos_in1 == '&' || *pos_in1 == '|' || *pos_in1 == '*')) { junk_pos277 = pos_in1 + 1; junk_pos278 = (void*) *pos_in1; goto fail; } else goto label279;
 label279:
  pos271 = pos_in1; result273 = 0; goto label272;
 label272:
  { const char *pos_out; void *ok_val; if(f_char(r, pos271, end, &pos_out, &ok_val)) { pos274 = pos_out; result276 = ok_val; goto label275; } else goto fail; }
 label275:
  pos261 = pos274;
  { void *c = result276; result263 = (void*) c; }
  goto label262;
 label262:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(r, pos261, end, &pos_out, &ok_val)) { pos264 = pos_out; result266 = ok_val; goto label265; } else goto label267; }
 label267:
  { const char *pos_out; void *ok_val; if(f_null(r, pos261, end, &pos_out, &ok_val)) { pos268 = pos_out; result270 = ok_val; goto label269; } else goto fail; }
 label269:
  pos264 = pos268;
  { void *c = result263; result266 = 0; }
  goto label265;
 label265:
  pos_out1 = pos264;
  { void *rest = result266; void *c = result263; ok_val1 = char_cons(r, (int) c, rest); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pathname(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos281;
  void *result283;
  const char *junk_pos290;
  const char *junk_pos291;
  const char *junk_pos293;
  const char *junk_pos294;
  const char *pos284;
  void *result286;
  const char *pos287;
  void *result289;
  if(pos_in1 < end && (('a' <= *pos_in1 && *pos_in1 <= 'z') || ('A' <= *pos_in1 && *pos_in1 <= 'Z') || ('0' <= *pos_in1 && *pos_in1 <= '9') || *pos_in1 == '_' || *pos_in1 == '/' || *pos_in1 == '.' || *pos_in1 == '~')) { junk_pos293 = pos_in1 + 1; junk_pos294 = (void*) *pos_in1; goto label292; } else goto label295;
 label295:
  junk_pos290 = pos_in1; junk_pos291 = 0; goto fail;
 label292:
  pos281 = pos_in1; result283 = 0; goto label282;
 label282:
  { const char *pos_out; void *ok_val; if(f_pathname_aux(r, pos281, end, &pos_out, &ok_val)) { pos284 = pos_out; result286 = ok_val; goto label285; } else goto fail; }
 label285:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos284, end, &pos_out, &ok_val)) { pos287 = pos_out; result289 = ok_val; goto label288; } else goto fail; }
 label288:
  pos_out1 = pos287;
  { void *s = result286; ok_val1 = s; }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arg(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos304;
  void *result306;
  const char *pos301;
  void *result303;
  const char *pos298;
  void *result300;
  { const char *pos_out; void *ok_val; if(f_option(r, pos_in1, end, &pos_out, &ok_val)) { pos304 = pos_out; result306 = ok_val; goto label305; } else goto label296; }
 label305:
  pos_out1 = pos304;
  { void *s = result306; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label296:
  { const char *pos_out; void *ok_val; if(f_string_literal(r, pos_in1, end, &pos_out, &ok_val)) { pos301 = pos_out; result303 = ok_val; goto label302; } else goto label297; }
 label302:
  pos_out1 = pos301;
  { void *s = result303; ok_val1 = mk_arg_string(r, s); }
  goto ok;
 label297:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos_in1, end, &pos_out, &ok_val)) { pos298 = pos_out; result300 = ok_val; goto label299; } else goto fail; }
 label299:
  pos_out1 = pos298;
  { void *f = result300; ok_val1 = mk_arg_filename(r, f); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist4(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos308;
  void *result310;
  const char *pos311;
  void *result313;
  const char *pos314;
  void *result316;
  { const char *pos_out; void *ok_val; if(f_c_open(r, pos_in1, end, &pos_out, &ok_val)) { pos308 = pos_out; result310 = ok_val; goto label309; } else goto label307; }
 label309:
  { const char *pos_out; void *ok_val; if(f_arglist1(r, pos308, end, &pos_out, &ok_val)) { pos311 = pos_out; result313 = ok_val; goto label312; } else goto label307; }
 label312:
  { const char *pos_out; void *ok_val; if(f_c_close(r, pos311, end, &pos_out, &ok_val)) { pos314 = pos_out; result316 = ok_val; goto label315; } else goto label307; }
 label315:
  pos_out1 = pos314;
  { void *l = result313; ok_val1 = l; }
  goto ok;
 label307:
  { const char *pos_out; void *ok_val; if(f_arg(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist3(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos321;
  void *result323;
  const char *pos324;
  void *result326;
  const char *pos318;
  void *result320;
  { const char *pos_out; void *ok_val; if(f_arglist4(r, pos_in1, end, &pos_out, &ok_val)) { pos321 = pos_out; result323 = ok_val; goto label322; } else goto label317; }
 label322:
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos321, end, &pos_out, &ok_val)) { pos324 = pos_out; result326 = ok_val; goto label325; } else goto label317; }
 label325:
  pos_out1 = pos324;
  { void *a2 = result326; void *a1 = result323; ok_val1 = mk_arg_cat(r, a1, a2); }
  goto ok;
 label317:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos318 = pos_out; result320 = ok_val; goto label319; } else goto fail; }
 label319:
  pos_out1 = pos318;
  { ok_val1 = mk_arg_empty(r); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist2(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos328;
  void *result330;
  const char *pos331;
  void *result333;
  const char *pos334;
  void *result336;
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos_in1, end, &pos_out, &ok_val)) { pos328 = pos_out; result330 = ok_val; goto label329; } else goto label327; }
 label329:
  { const char *pos_out; void *ok_val; if(f_plus(r, pos328, end, &pos_out, &ok_val)) { pos331 = pos_out; result333 = ok_val; goto label332; } else goto label327; }
 label332:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos331, end, &pos_out, &ok_val)) { pos334 = pos_out; result336 = ok_val; goto label335; } else goto label327; }
 label335:
  pos_out1 = pos334;
  { void *fs = result336; void *a = result330; ok_val1 = mk_arg_cat(r, a, mk_arg_ambient(r, fs)); }
  goto ok;
 label327:
  { const char *pos_out; void *ok_val; if(f_arglist3(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_arglist1(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos338;
  void *result340;
  const char *pos341;
  void *result343;
  const char *pos344;
  void *result346;
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos_in1, end, &pos_out, &ok_val)) { pos338 = pos_out; result340 = ok_val; goto label339; } else goto label337; }
 label339:
  { const char *pos_out; void *ok_val; if(f_arrow(r, pos338, end, &pos_out, &ok_val)) { pos341 = pos_out; result343 = ok_val; goto label342; } else goto label337; }
 label342:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos341, end, &pos_out, &ok_val)) { pos344 = pos_out; result346 = ok_val; goto label345; } else goto label337; }
 label345:
  pos_out1 = pos344;
  { void *a2 = result346; void *a1 = result340; ok_val1 = mk_arg_cat(r, mk_arg_read(r, a1), mk_arg_write(r, a2)); }
  goto ok;
 label337:
  { const char *pos_out; void *ok_val; if(f_arglist2(r, pos_in1, end, &pos_out, &ok_val)) { pos_out1 = pos_out; ok_val1 = ok_val; goto ok; } else goto fail; }
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_invocation(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos347;
  void *result349;
  const char *pos360;
  void *result362;
  const char *pos357;
  void *result359;
  const char *pos350;
  void *result352;
  const char *pos353;
  void *result355;
  { const char *pos_out; void *ok_val; if(f_bang_bang(r, pos_in1, end, &pos_out, &ok_val)) { pos360 = pos_out; result362 = ok_val; goto label361; } else goto label356; }
 label361:
  pos347 = pos360;
  { result349 = 1; }
  goto label348;
 label356:
  { const char *pos_out; void *ok_val; if(f_null(r, pos_in1, end, &pos_out, &ok_val)) { pos357 = pos_out; result359 = ok_val; goto label358; } else goto fail; }
 label358:
  pos347 = pos357;
  { result349 = 0; }
  goto label348;
 label348:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos347, end, &pos_out, &ok_val)) { pos350 = pos_out; result352 = ok_val; goto label351; } else goto fail; }
 label351:
  { const char *pos_out; void *ok_val; if(f_arglist1(r, pos350, end, &pos_out, &ok_val)) { pos353 = pos_out; result355 = ok_val; goto label354; } else goto fail; }
 label354:
  pos_out1 = pos353;
  { void *args = result355; void *cmd = result352; void *no_sec = result349; ok_val1 = mk_invocation(r, no_sec, cmd, args); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_pipeline(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos367;
  void *result369;
  const char *pos370;
  void *result372;
  const char *pos373;
  void *result375;
  const char *pos364;
  void *result366;
  { const char *pos_out; void *ok_val; if(f_invocation(r, pos_in1, end, &pos_out, &ok_val)) { pos367 = pos_out; result369 = ok_val; goto label368; } else goto label363; }
 label368:
  { const char *pos_out; void *ok_val; if(f_pipe_bar(r, pos367, end, &pos_out, &ok_val)) { pos370 = pos_out; result372 = ok_val; goto label371; } else goto label363; }
 label371:
  { const char *pos_out; void *ok_val; if(f_pipeline(r, pos370, end, &pos_out, &ok_val)) { pos373 = pos_out; result375 = ok_val; goto label374; } else goto label363; }
 label374:
  pos_out1 = pos373;
  { void *pl = result375; void *inv = result369; ok_val1 = mk_pipeline_cons(r, inv, pl); }
  goto ok;
 label363:
  { const char *pos_out; void *ok_val; if(f_invocation(r, pos_in1, end, &pos_out, &ok_val)) { pos364 = pos_out; result366 = ok_val; goto label365; } else goto fail; }
 label365:
  pos_out1 = pos364;
  { void *inv = result366; ok_val1 = mk_pipeline_inv(r, inv); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_command(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  const char *pos423;
  void *result425;
  const char *pos426;
  void *result428;
  const char *pos429;
  void *result431;
  const char *pos417;
  void *result419;
  const char *pos420;
  void *result422;
  const char *pos405;
  void *result407;
  const char *pos408;
  void *result410;
  const char *pos411;
  void *result413;
  const char *pos414;
  void *result416;
  const char *pos393;
  void *result395;
  const char *pos396;
  void *result398;
  const char *pos399;
  void *result401;
  const char *pos402;
  void *result404;
  const char *pos380;
  void *result382;
  const char *pos383;
  void *result385;
  const char *pos390;
  void *result392;
  const char *pos387;
  void *result389;
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos423 = pos_in1 + 2; result425 = 0; goto label424; } else goto label376;
 label424:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos423, end, &pos_out, &ok_val)) { pos426 = pos_out; result428 = ok_val; goto label427; } else goto label376; }
 label427:
  { const char *pos_out; void *ok_val; if(f_pathname(r, pos426, end, &pos_out, &ok_val)) { pos429 = pos_out; result431 = ok_val; goto label430; } else goto label376; }
 label430:
  pos_out1 = pos429;
  { void *dir = result431; ok_val1 = mk_chdir(r, dir); }
  goto ok;
 label376:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'c' && pos_in1[1] == 'd') { pos417 = pos_in1 + 2; result419 = 0; goto label418; } else goto label377;
 label418:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos417, end, &pos_out, &ok_val)) { pos420 = pos_out; result422 = ok_val; goto label421; } else goto label377; }
 label421:
  pos_out1 = pos420;
  { ok_val1 = mk_chdir(r, char_cons(r, '~', 0)); }
  goto ok;
 label377:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'f' && pos_in1[1] == 'g') { pos405 = pos_in1 + 2; result407 = 0; goto label406; } else goto label378;
 label406:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos405, end, &pos_out, &ok_val)) { pos408 = pos_out; result410 = ok_val; goto label409; } else goto label378; }
 label409:
  { const char *pos_out; void *ok_val; if(f_number(r, pos408, end, &pos_out, &ok_val)) { pos411 = pos_out; result413 = ok_val; goto label412; } else goto label378; }
 label412:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos411, end, &pos_out, &ok_val)) { pos414 = pos_out; result416 = ok_val; goto label415; } else goto label378; }
 label415:
  pos_out1 = pos414;
  { void *n = result413; ok_val1 = mk_command_fg(r, n); }
  goto ok;
 label378:
  if(pos_in1 + 2 <= end && pos_in1[0] == 'b' && pos_in1[1] == 'g') { pos393 = pos_in1 + 2; result395 = 0; goto label394; } else goto label379;
 label394:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos393, end, &pos_out, &ok_val)) { pos396 = pos_out; result398 = ok_val; goto label397; } else goto label379; }
 label397:
  { const char *pos_out; void *ok_val; if(f_number(r, pos396, end, &pos_out, &ok_val)) { pos399 = pos_out; result401 = ok_val; goto label400; } else goto label379; }
 label400:
  { const char *pos_out; void *ok_val; if(f_ws(r, pos399, end, &pos_out, &ok_val)) { pos402 = pos_out; result404 = ok_val; goto label403; } else goto label379; }
 label403:
  pos_out1 = pos402;
  { void *n = result401; ok_val1 = mk_command_bg(r, n); }
  goto ok;
 label379:
  { const char *pos_out; void *ok_val; if(f_pipeline(r, pos_in1, end, &pos_out, &ok_val)) { pos380 = pos_out; result382 = ok_val; goto label381; } else goto fail; }
 label381:
  { const char *pos_out; void *ok_val; if(f_ampersand(r, pos380, end, &pos_out, &ok_val)) { pos390 = pos_out; result392 = ok_val; goto label391; } else goto label386; }
 label391:
  pos383 = pos390;
  { void *cmd = result382; result385 = 1; }
  goto label384;
 label386:
  { const char *pos_out; void *ok_val; if(f_null(r, pos380, end, &pos_out, &ok_val)) { pos387 = pos_out; result389 = ok_val; goto label388; } else goto fail; }
 label388:
  pos383 = pos387;
  { void *cmd = result382; result385 = 0; }
  goto label384;
 label384:
  pos_out1 = pos383;
  { void *bg_flag = result385; void *cmd = result382; ok_val1 = mk_command(r, cmd, bg_flag); }
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_fail(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  goto fail;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}

int f_null(region_t r, const char *pos_in1, const char *end, const char **pos_out_p, void **ok_val_p)
{
  const char *pos_out1;
  void *ok_val1;
  pos_out1 = pos_in1;
  ok_val1 = 0;
  goto ok;
 ok:
  *pos_out_p = pos_out1;
  *ok_val_p = ok_val1;
  return 1;
 fail:
  return 0;
}
