#!/bin/sh

# Copyright (C) 2004 Mark Seaborn
#
# This file is part of Plash.
#
# Plash is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# Plash is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Plash; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
# USA.


set -e

echo Writing mrs/shell-parse.c
(echo '/* This file is automatically generated from shell.gram */';
 echo '#include "region.h"';
 echo '#include "shell.h"';
 echo '#include "shell-variants.h"';
 ./src/parser-generator/c_compile_grammar --extra-arg r 'region_t r' src/shell.gram
) >src/shell-parse.c
